import{buildWaveSand}from './kernel.mjs';import{makeWaveGround,waveHeights}from './terrain.mjs';import{mkdirSync,writeFileSync}from'node:fs';import{dirname,resolve}from'node:path';
const data=makeWaveGround();const output=resolve(process.argv[2]||'scripts/spikes/wave-sand/preview.html');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sand on waveform · Mojulo spike</title>
<style>*{box-sizing:border-box}:root{color-scheme:dark}body{margin:0;background:#0d1721;color:#eaf0f3;font:15px system-ui}main{max-width:1120px;margin:30px auto;padding:0 22px}h1{font-size:36px;letter-spacing:-1px;margin:12px 0}.eyebrow{font:12px monospace;letter-spacing:2px;color:#73c2cf}p{color:#a5b8c5;line-height:1.6;max-width:950px}.controls{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin:18px 0}button,select{padding:9px 12px;background:#23384a;color:#eef2f4;border:1px solid #4b677e;border-radius:7px;font:inherit}label{display:flex;align-items:center;gap:8px}input{accent-color:#e5bb79}canvas{display:block;width:100%;height:auto;background:#122230;border:1px solid #314b60;border-radius:12px;touch-action:none}.metrics{font:14px monospace;color:#e5c48e;margin:15px 0}.hint{color:#74c8d5}</style>
<main><div class="eyebrow">MOJULO / WAVE-FIELD → GRANULAR LAYER</div><h1>Sand on a waveform</h1><p>The ground comes from Mojulo’s wave-field sampler. Sand moves according to the combined ground height and sand depth. Changing the waveform changes where it can rest.</p>
<div class="controls"><button id="pour">Pour at marker</button><button id="sheet">Add sand sheet</button><button id="reset">Reset</button><button id="pause">Pause sand</button></div>
<div class="controls"><label>Amplitude <input id="amp" type="range" min="0" max="2.5" step="0.05" value="1.4"><span id="ampValue"></span></label><label>Wave phase <input id="phase" type="range" min="0" max="6.283185" step="0.02" value="0"></label><label><input id="animate" type="checkbox">Animate ground</label><label>View <select id="layer"><option value="sand">Ground + sand</option><option value="ground">Ground only</option></select></label></div>
<div class="controls"><label>Marker X <input id="mx" type="range" min="2" max="30" step="1" value="16"></label><label>Marker Y <input id="my" type="range" min="2" max="30" step="1" value="16"></label></div>
<canvas id="view" width="1080" height="650" aria-label="Orbitable 3D height surface showing sand on waveform terrain"></canvas><div id="stats" class="metrics"></div>
<p class="hint">Drag to orbit. Set amplitude to zero for flat ground; increase it to see sand redistribute. Change phase to move the troughs beneath the same sand mass. Gold = sand layer · blue = uncovered ground · cyan = pour marker.</p>
<p>A conservative 2.5D depth layer displayed in 3D, with an approximate repose slope. The terrain is sampled from the real wave primitive; neighbor relaxation supplies the granular behavior. Moving terrain carries the layer quasi-statically. No overhangs, inertia, airborne grains, or particle-pair collisions.</p></main><script>
const buildWaveSand=${buildWaveSand.toString()},waveHeights=${waveHeights.toString()},data=${JSON.stringify(data)};
const $=id=>document.getElementById(id),ctx=$('view').getContext('2d');let s,yaw=0.65,pitch=0.65,drag=null,dirty=true,paused=false,last=null,acc=0,phase=0,metric={checked:0,moved:0},cost=0;
function sheet(){for(let y=9;y<=23;y++)for(let x=9;x<=23;x++)s.deposit(x,y,24);dirty=true}
function ground(){s.setGround(waveHeights(data,+$('amp').value,phase));dirty=true}
function reset(){phase=0;$('phase').value=0;$('amp').value=1.4;$('animate').checked=false;s=buildWaveSand({n:33,spacing:data.spacing,ground:waveHeights(data,1.4)});sheet();metric={checked:0,moved:0};acc=0;cost=0;dirty=true}
function project(x,y,z){const a=x*Math.cos(yaw)-y*Math.sin(yaw),b=x*Math.sin(yaw)+y*Math.cos(yaw);return[540+a*52,355+(b*Math.sin(pitch)-z*Math.cos(pitch))*52,b*Math.cos(pitch)+z*Math.sin(pitch)]}
function draw(){ctx.clearRect(0,0,1080,650);const g=s.ground(),m=s.mass,show=$('layer').value==='sand',z=i=>g[i]+(show?m[i]*s.grainHeight:0),quads=[];
for(let y=0;y<32;y++)for(let x=0;x<32;x++){const ids=[y*33+x,y*33+x+1,(y+1)*33+x+1,(y+1)*33+x],pts=ids.map(i=>project(-6+(i%33)*data.spacing,-6+Math.floor(i/33)*data.spacing,z(i)));const cover=show?ids.reduce((a,i)=>a+m[i],0)/4:0;const slope=(z(ids[1])-z(ids[0]))/data.spacing,shade=Math.max(0.55,Math.min(1.1,0.85-slope*0.12));const base=cover>0?[222,185,123]:[46,92,119];quads.push({pts,depth:pts.reduce((a,p)=>a+p[2],0)/4,fill:'rgb('+base.map(v=>Math.round(v*shade)).join(',')+')',cover})}
quads.sort((a,b)=>a.depth-b.depth);for(const q of quads){ctx.beginPath();q.pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=q.fill;ctx.fill();ctx.strokeStyle=q.cover?'#b8956240':'#72bec866';ctx.lineWidth=0.6;ctx.stroke()}
const x=+$('mx').value,y=+$('my').value,i=y*33+x,p=project(-6+x*data.spacing,-6+y*data.spacing,z(i)+0.05);ctx.strokeStyle='#8ae5ed';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p[0],p[1],7,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(p[0],p[1]-9);ctx.lineTo(p[0],p[1]-35);ctx.stroke();const st=s.stats();$('ampValue').textContent=(+$('amp').value).toFixed(2)+' m';$('stats').textContent=st.total+' mass units · '+st.active+' pending cells · '+metric.checked+' checks / tick · '+cost.toFixed(3)+' ms simulation / tick';dirty=false}
$('amp').oninput=ground;$('phase').oninput=()=>{phase=+$('phase').value;ground()};$('mx').oninput=$('my').oninput=()=>dirty=true;$('layer').onchange=()=>dirty=true;
$('pour').onclick=()=>{s.deposit(+$('mx').value,+$('my').value,256);dirty=true};$('sheet').onclick=sheet;$('reset').onclick=reset;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume sand':'Pause sand';acc=0};
$('view').onpointerdown=e=>{drag=[e.clientX,e.clientY];$('view').setPointerCapture(e.pointerId)};$('view').onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*0.01;pitch=Math.max(0.15,Math.min(1.3,pitch+(e.clientY-drag[1])*0.01));drag=[e.clientX,e.clientY];dirty=true};$('view').onpointerup=$('view').onpointercancel=()=>drag=null;
function frame(now){if(last===null)last=now;const dt=Math.min(0.1,(now-last)/1000);last=now;if(!paused){if($('animate').checked){phase=(phase+dt*0.45)%(2*Math.PI);$('phase').value=phase;ground()}acc+=dt*30;let work=0;while(acc>=1&&work<4){const before=s.stats().active,start=performance.now();metric=s.step();cost=performance.now()-start;if(metric.moved||metric.active!==before)dirty=true;acc--;work++}}if(dirty)draw();requestAnimationFrame(frame)}reset();draw();requestAnimationFrame(frame);
</script></html>`;mkdirSync(dirname(output),{recursive:true});writeFileSync(output,html);console.log(output);
