/**
 * brickster 16-bit skin — the same game WORLD resolved through the
 * 16bit register. brickster-core.js is untouched; this module is a
 * second pure resolution over the identical state, which makes the
 * 8-bit/16-bit pair the cleanest possible demonstration of the render
 * seam: one reducer, two registers, byte-stable each.
 *
 * Under the raster/overlay doctrine the register seam lives entirely in
 * the WORLD: SCORE / LINES / LEVEL and the hold/next labels are real
 * text, register-independent, so this skin ships no glyphs and reuses
 * resolveOverlay / emitComposedSvg from the 8-bit skin — the picture
 * side is all that changes register.
 *
 * What the wider budget buys the world (15 colors + transparent):
 * - gem-cut piece tiles: a 6-shade ramp per tetromino with a corner
 *   glint, generated by one deterministic bevel function.
 * - a layered frame: a starfield gradient backdrop lattice UNDER the
 *   dynamic nametable (the SNES background-layer move), a subtle
 *   cell-grid well floor, and a machined metal frame.
 * - a dithered ghost that reads translucent instead of hollow.
 */

import { emitPixelSvg } from '../pixelizer.js';
import { WELL_W, WELL_H, HIDDEN, cellsOf, dropDistance } from '../brickster-core.js';
import { previewRows, resolveOverlay, emitComposedSvg } from '../brickster-skin.js';

const COLS16 = WELL_W + 2; // wall + 10 well + wall
const ROWS16 = WELL_H - HIDDEN + 2; // top wall + 20 visible + bottom wall

// [darkest, dark, mid, light, lighter, glint] per piece
const GEM_RAMPS = {
  i: ['#043038', '#086874', '#00a8b8', '#40d0dc', '#90ecf0', '#d8fcfc'],
  j: ['#101c58', '#1c3490', '#3050c8', '#6080e8', '#98b0f8', '#d0dcfc'],
  l: ['#4c2404', '#8c4808', '#c87010', '#e89838', '#f8c070', '#fce0b0'],
  o: ['#4c3c04', '#8c7008', '#c8a410', '#e8cc38', '#f8e470', '#fcf4b0'],
  s: ['#0c3808', '#1c6c14', '#30a024', '#60c848', '#a0e880', '#d8f8c0'],
  t: ['#2c0c44', '#54187c', '#8030b0', '#a858d8', '#d090f0', '#ecc8fc'],
  z: ['#440c14', '#7c1824', '#b02836', '#d85060', '#f09098', '#fcccd0'],
};

/** One bevel to cut them all: light from top-left, glint at the corner, gradient interior. */
function gemTile(ramp) {
  const cells = [];
  for (let y = 0; y < 8; y++) {
    const r = [];
    for (let x = 0; x < 8; x++) {
      if ((x === 1 && y === 1) || (x === 2 && y === 1) || (x === 1 && y === 2)) r.push('6');
      else if (y === 7 || x === 7) r.push(x === 0 || y === 0 ? '2' : '1');
      else if (y === 0 || x === 0) r.push('5');
      else r.push(x + y <= 5 ? '4' : x + y <= 9 ? '3' : '2');
    }
    cells.push(r.join(''));
  }
  return { size: [8, 8], palette: ramp, cells };
}

const frameTile = gemTile(['#20202c', '#40404c', '#60606c', '#84848c', '#a8a8b0', '#d0d0d8']);

// empty well cell: near-black with a 1px cell seam — the grid reads without shouting
const wellTile = {
  size: [8, 8],
  palette: ['#100e24', '#1a1636'],
  cells: [...Array.from({ length: 7 }, () => '11111112'), '22222222'],
};

// translucent-reading ghost: solid outline, 1×1 checker interior
const ghostTile = {
  size: [8, 8],
  palette: ['#50506c'],
  cells: Array.from({ length: 8 }, (_, y) =>
    Array.from({ length: 8 }, (_, x) =>
      (x === 0 || y === 0 || x === 7 || y === 7 ? '1' : (x + y) % 2 ? '1' : '.')).join('')),
};

// ---- static backdrop lattice: a starfield gradient under everything ----
const solid16 = (color) => ({ size: [8, 8], palette: [color], cells: Array.from({ length: 8 }, () => '11111111') });
const dither16 = (a, b) => ({
  size: [8, 8],
  palette: [a, b],
  cells: Array.from({ length: 8 }, (_, y) =>
    Array.from({ length: 8 }, (_, x) => (y < 3 ? '1' : y < 5 ? ((x + y) % 2 ? '2' : '1') : '2')).join('')),
});
const star16 = (bg, cols) => {
  const t = solid16(bg);
  t.palette = [bg, '#8c88b0'];
  t.cells = t.cells.map((r, y) => {
    const hit = cols.filter(([, py]) => py === y).map(([x]) => x);
    if (!hit.length) return r;
    const chars = r.split('');
    for (const x of hit) chars[x] = '2';
    return chars.join('');
  });
  return t;
};

const DEPTHS = ['#0c0a18', '#141026', '#1e1838', '#2a2150'];
const rep = (ch, n = COLS16) => ch.repeat(n);
const backdropLayer = {
  tileSize: [8, 8],
  bank: {
    b0: solid16(DEPTHS[0]), b1: solid16(DEPTHS[1]), b2: solid16(DEPTHS[2]), b3: solid16(DEPTHS[3]),
    d0: dither16(DEPTHS[0], DEPTHS[1]), d1: dither16(DEPTHS[1], DEPTHS[2]), d2: dither16(DEPTHS[2], DEPTHS[3]),
    x0: star16(DEPTHS[0], [[3, 2], [6, 5]]), x1: star16(DEPTHS[1], [[5, 3]]),
  },
  legend: { a: 'b0', b: 'b1', c: 'b2', d: 'b3', p: 'd0', q: 'd1', r: 'd2', x: 'x0', y: 'x1' },
  rows: [
    'aaxaaaaaaaxa'.slice(0, COLS16),
    rep('a'),
    'aaaaaxaaaaax'.slice(0, COLS16),
    rep('a'),
    rep('p'),
    rep('b'),
    'bbbybbbbbbyb'.slice(0, COLS16),
    rep('b'),
    rep('b'),
    rep('q'),
    rep('c'),
    rep('c'),
    rep('c'),
    rep('c'),
    rep('r'),
    ...Array.from({ length: 7 }, () => rep('d')),
  ],
};

const BANK16 = {
  ...Object.fromEntries(Object.entries(GEM_RAMPS).map(([ch, ramp]) => [`gem-${ch}`, gemTile(ramp)])),
  frame: frameTile,
  well: wellTile,
  ghost: ghostTile,
};

const LEGEND16 = {
  ...Object.fromEntries(Object.keys(GEM_RAMPS).map((ch) => [ch, `gem-${ch}`])),
  '#': 'frame',
  '-': 'well',
  g: 'ghost',
};

/** Pure state → 16bit WORLD recipe: backdrop lattice under the dynamic nametable. */
export function buildWorldRecipe16(state) {
  const well = [];
  for (let y = HIDDEN; y < WELL_H; y++) well.push([...state.board[y]].map((ch) => (ch === '.' ? '-' : ch)));
  if (state.active) {
    const { type, rot, x, y } = state.active;
    for (const [cx, cy] of cellsOf(type, rot, x, y + dropDistance(state))) {
      if (cy >= HIDDEN && well[cy - HIDDEN][cx] === '-') well[cy - HIDDEN][cx] = 'g';
    }
    for (const [cx, cy] of cellsOf(type, rot, x, y)) {
      if (cy >= HIDDEN) well[cy - HIDDEN][cx] = type.toLowerCase();
    }
  }
  const wellRows = well.map((row) => row.join(''));

  const dynamicLayer = {
    tileSize: [8, 8],
    bank: BANK16,
    legend: LEGEND16,
    rows: [
      '#'.repeat(COLS16),
      ...wellRows.map((row) => `#${row}#`),
      '#'.repeat(COLS16),
    ],
  };

  return {
    kind: 'pixel-map',
    register: '16bit',
    size: [COLS16 * 8, ROWS16 * 8],
    background: DEPTHS[0],
    tiles: [backdropLayer, dynamicLayer],
    sprites: {},
    placements: [],
  };
}

export const renderWorldSvg16 = (state, scale = 4) => emitPixelSvg(buildWorldRecipe16(state), 0, { scale });

/** A single piece as a 16bit gem-tile preview raster — the diegetic hold/next. */
export function buildPreviewRecipe16(type) {
  const rows = type ? previewRows(type) : ['....', '....'];
  return {
    kind: 'pixel-map',
    register: '16bit',
    size: [4 * 8, 2 * 8],
    background: null,
    tiles: { tileSize: [8, 8], bank: BANK16, legend: LEGEND16, rows },
    sprites: {},
    placements: [],
  };
}

export const renderPreviewSvg16 = (type, scale = 4) => emitPixelSvg(buildPreviewRecipe16(type), 0, { scale });

/** The shared text HUD over the 16bit world — the overlay is register-independent. */
export const emitComposedSvg16 = (state, { scale = 4 } = {}) =>
  emitComposedSvg(state, {
    scale,
    renderWorld: renderWorldSvg16,
    renderPreview: renderPreviewSvg16,
    bg: '#0a0814',
  });

export { resolveOverlay };
