import assert from 'node:assert/strict';
import { printWaveManji } from '../../../lib/graph/polygonizer/wave-manji.js';
import { buildParticleVacuum } from './kernel.mjs';
const template=printWaveManji({singularity:{x:0,y:0,z:0},script:'mandala',params:{N:3,radius:0.15,lobeDepth:0.035},samples:24}).polylines.map(l=>l.map(p=>[p.x,p.y,p.z]));
const k=buildParticleVacuum(template),p=[{id:'a',anchor:[0,0,0]},{id:'b',anchor:[5,0,0]}];
const e={id:'a',time:1,center:[0,0,0],radius:1,impulse:[2,0,1]};
assert.deepEqual(k.sample(p,[],0),k.sample(p,[],100));
assert.deepEqual(k.sample(p,[e],0.9),k.sample(p,[],0.9));
assert.deepEqual(k.sample(p,[e],2)[1],k.sample(p,[],2)[1]);
assert.notDeepEqual(k.sample(p,[e],2)[0].center,p[0].anchor);
assert.deepEqual(k.sample(p,[e],6),k.sample(p,[e],60));
const follow={id:'b',time:2,center:k.sample(p,[e],2)[0].center,radius:0.1,impulse:[0,1,0]};
assert.equal(k.sample(p,[e,follow],3)[0].contacts,2);
assert.deepEqual(k.sample(p,[e,follow],3),k.sample(p,[follow,e],3));
const expected=k.sample(p,[e,follow],3);
for(let t=0;t<3;t+=1/60)k.sample(p,[e,follow],t);
assert.deepEqual(k.sample(p,[e,follow],3),expected);
assert(expected.flatMap(s=>s.polylines.flat(2)).every(Number.isFinite));
assert.throws(()=>k.sample(p,[{...e,radius:NaN}],2));
assert.throws(()=>k.sample([p[0],p[0]],[],2));
console.log('PASS: stasis, future events, locality, motion, settling, current-position contact, reordered replay, seeking, finite geometry, input validation.');
