/**
 * godot-project.js — the Godot 4 pack emitter (godot-handoff.plan.md G1 +
 * game scope, reshaped by G6: kernel architecture).
 *
 * Since kernel 0.1.0 the pack ships DATA and the versioned hand-authored
 * kernel (lib/graph/scene/godot-kernel/, copied in by the driver) performs
 * it: level.tscn is a three-line stub pointing kernel/level.gd at
 * score.json; game packs add game.json + a menu stub + the Game autoload
 * (kernel/game.gd). All promotion — ground, colliders, cameras, walker, the
 * full mechanics vocabulary, material fixup — happens in the kernel at
 * runtime. One score, two instruments: game-shell.js is the web kernel,
 * godot-kernel/ is this one.
 *
 * The emitter's remaining jobs: scene stubs, project.godot, export presets,
 * .gitignore, and the provenance README with the honest-loss ledger (which
 * shrank — the vocabulary is now interpreted, not ledgered).
 * Everything emitted is deterministic text: no dice, no timestamps, stable
 * ordering, no uids (path fallback, the plan's uid note).
 */

const MECHANICS_VOCAB = ['reach-exit', 'collect', 'hazard-damage', 'fail-on-death', 'survive'];
const COMPLETION_KINDS = ['reach-exit', 'survive'];

const fmt = (n) => {
  const v = Math.round(n * 1e6) / 1e6;
  return Object.is(v, -0) ? '0' : String(v);
};
const gdName = (s) => String(s).replace(/[^A-Za-z0-9_]/g, '_');
const gdStr = (s) => JSON.stringify(String(s));
const GITIGNORE = '.godot/\nbuild/\n';

function buildPresets(ref) {
  return `[preset.0]

name="Web"
platform="Web"
runnable=true
export_filter="all_resources"
include_filter="*.json"
export_path="build/web/index.html"

[preset.0.options]

variant/thread_support=false

[preset.1]

name="macOS"
platform="macOS"
runnable=true
export_filter="all_resources"
include_filter="*.json"
export_path="build/mac/${gdName(ref)}.zip"

[preset.1.options]

application/bundle_identifier="com.mojulo.${gdName(ref)}"
`;
}

function buildProjectGodot({ title, mainScene, autoloadGame = false }) {
  return `; generated by mojulo export-godot — do not hand-edit; re-mint from recipe/
config_version=5

[application]

config/name=${gdStr(title)}
run/main_scene="res://${mainScene}"
${autoloadGame ? `
[autoload]

Game="*res://kernel/game.gd"
` : ''}
[rendering]

renderer/rendering_method.web="gl_compatibility"
`;
}

const ledgerLines = (ledger) => Object.entries(ledger)
  .map(([k, v]) => `- \`${k}\`${v.count != null ? ` ×${v.count}` : ''}${v.kinds ? ` (${v.kinds.join(', ')})` : ''} — ${v.note}`)
  .join('\n');

/** The per-level scene stub: kernel/level.gd pointed at the level's data. */
function levelStub({ resBase = '', glbFile = 'model.glb', musicPath = null, musicDb = null }) {
  const props = [`score_path = "res://${resBase}score.json"`];
  if (musicPath) props.push(`music_path = "res://${musicPath}"`);
  if (musicDb != null) props.push(`music_db = ${fmt(musicDb)}`);
  return `[gd_scene load_steps=3 format=3]

[ext_resource type="PackedScene" path="res://${resBase}${glbFile}" id="model"]
[ext_resource type="Script" path="res://kernel/level.gd" id="kernel"]

[node name="Level" type="Node3D"]
script = ExtResource("kernel")
${props.join('\n')}

[node name="World" parent="." instance=ExtResource("model")]
`;
}

/** The honest-loss ledger for one level, post-kernel: the vocabulary is
 * interpreted now; only out-of-vocabulary gameplay and non-geometry channels
 * remain losses. */
function levelLedger(score, { gameMode = false } = {}) {
  const ledger = { ...score.ledger };
  ledger.entity_markers = {
    note: 'entities that baked no mesh (glyph/primitive bodies — export-side gap) render as gold placeholder markers; the web build is the reference look',
  };
  ledger.web_color_shift = {
    note: 'web preset renders via GL Compatibility, which reads vertex colours as sRGB — linear COLOR_0 draws darker there; desktop uses Forward+ and is colour-true',
  };
  if (score.ground != null) {
    ledger.promoted_ground = { note: 'implicit runtime ground plane promoted by the kernel — the collider AABBs are obstacle hulls only, never the floor' };
  }
  const kinds = (score.mechanics ?? []).map((m) => m?.kind).filter(Boolean);
  const interpreted = kinds.filter((k) => MECHANICS_VOCAB.includes(k));
  const unknown = kinds.filter((k) => !MECHANICS_VOCAB.includes(k));
  if (interpreted.length) {
    ledger.interpreted_mechanics = { count: interpreted.length, kinds: [...new Set(interpreted)], note: 'performed live by kernel/level.gd' };
  }
  if (unknown.length) {
    ledger.unknown_mechanics = { count: unknown.length, kinds: [...new Set(unknown)], note: 'outside the kernel vocabulary — do not travel' };
  }
  if (gameMode && !kinds.some((k) => COMPLETION_KINDS.includes(k))) {
    ledger.no_completion_path = {
      note: 'no completion mechanic — the authored win condition lives in the runtime, which does not travel; the level is an explorable arena (M returns to the menu)',
    };
  }
  return ledger;
}

/**
 * emitGodotProject — a standalone world pack: stub + shell + README.
 * The driver ships kernel/, model.glb, score.json, recipe/, audio/.
 */
export function emitGodotProject({ ref, score, manifestHash, glbFile = 'model.glb', audioFile = null, kernelVersion = '?', remint = null }) {
  const title = score.title ?? ref;
  const ledger = levelLedger(score);
  const files = [
    { file: 'project.godot', text: buildProjectGodot({ title, mainScene: 'level.tscn' }) },
    { file: 'level.tscn', text: levelStub({ glbFile, musicPath: audioFile }) },
    { file: 'export_presets.cfg', text: buildPresets(ref) },
    { file: '.gitignore', text: GITIGNORE },
    {
      file: 'README.md',
      text: `# ${title} — Godot handoff

A generated Godot 4 pack (mojulo \`export-godot\`). The world's truth lives
in \`recipe/\` — this whole folder is a derived artifact; re-mint it from the
recipe rather than hand-editing. The pack is DATA (\`score.json\`, the GLB,
audio) performed by the versioned mojulo-godot kernel in \`kernel/\`
(v${kernelVersion}) — one score, two instruments; the web build is the
reference performance.

## Provenance

- source ref: \`${ref}\`
- manifest sha256/16: \`${manifestHash}\`
- kernel: mojulo-godot ${kernelVersion}
- units: ${score.units}; frame converted z-up → y-up by the kernel, matching the GLB root
- re-mint: \`${remint ?? `node scripts/export-godot.mjs --ref ${ref}`}\` (from mojulo's \`control/\`)

## Open and play

Open the folder in Godot ≥4.5 (or \`godot --path .\`) and run. WASD/arrows to
walk, mouse to look, Space jumps, Esc frees the mouse${score.cameras?.length ? ', 0 toggles the authored camera framing' : ''}.

## What travelled, what didn't

${ledgerLines(ledger)}
`,
    },
  ];
  return { files, ledger };
}

/**
 * emitGodotGame — a game pack: per-level stubs + menu stub + shell + README.
 * The driver ships kernel/, game.json, per-level model.glb/score.json,
 * recipe/, audio/. levels: [{ ref, title, gate, score, audioFile, audioDb }].
 */
export function emitGodotGame({ ref, title, manifestHash, levels, music = {}, shellExtras = [], kernelVersion = '?', remint = null }) {
  const files = [];
  const ledger = {
    skipped_store: { note: 'store slices (character/inventory state) do not travel — only completion progression is kept (user://progress.cfg)' },
    levels: {},
  };
  if (shellExtras.length) {
    ledger.skipped_shell = {
      kinds: shellExtras,
      note: 'authored shell UI beyond the level list (menu structure, setup/hangar, difficulty, theme) does not travel — the kernel menu is a plain level table',
    };
  }
  const oddGates = levels.filter((lv) => lv.gate && !lv.gate.completed);
  if (oddGates.length) {
    ledger.gate_approximated = {
      count: oddGates.length,
      note: 'non-completion gates (store flags) approximated as unlocked — flag state does not travel',
    };
  }

  for (const lv of levels) {
    files.push({
      file: `levels/${lv.ref}/level.tscn`,
      text: levelStub({ resBase: `levels/${lv.ref}/`, musicPath: lv.audioFile ?? null, musicDb: lv.audioDb ?? null }),
    });
    ledger.levels[lv.ref] = levelLedger(lv.score, { gameMode: true });
  }

  const menuExt = [`[ext_resource type="Script" path="res://kernel/menu.gd" id="menu_gd"]`];
  if (music.menuFile) menuExt.push(`[ext_resource type="AudioStream" path="res://${music.menuFile}" id="music"]`);
  files.push({
    file: 'menu.tscn',
    text: `[gd_scene load_steps=${menuExt.length + 1} format=3]

${menuExt.join('\n')}

[node name="Menu" type="Control"]
anchor_right = 1.0
anchor_bottom = 1.0
script = ExtResource("menu_gd")
${music.menuFile ? `
[node name="Music" type="AudioStreamPlayer" parent="."]${music.menuDb != null ? `\nvolume_db = ${fmt(music.menuDb)}` : ''}\nstream = ExtResource("music")\n` : ''}`,
  });

  files.push({ file: 'project.godot', text: buildProjectGodot({ title, mainScene: 'menu.tscn', autoloadGame: true }) });
  files.push({ file: 'export_presets.cfg', text: buildPresets(ref) });
  files.push({ file: '.gitignore', text: GITIGNORE });

  const levelList = levels
    .map((lv, i) => `${i + 1}. ${lv.title ?? lv.ref} (\`${lv.ref}\`)${lv.gate?.completed ? ` — unlocks after \`${lv.gate.completed}\`` : ''}`)
    .join('\n');
  const perLevelLedgers = levels
    .map((lv) => `### \`${lv.ref}\`\n\n${ledgerLines(ledger.levels[lv.ref])}`)
    .join('\n\n');
  files.push({
    file: 'README.md',
    text: `# ${title} — Godot handoff (game)

A generated Godot 4 pack (mojulo \`export-godot\`, game scope). The game's
truth lives in \`recipe/\` — this whole folder is a derived artifact; re-mint
it from the recipe rather than hand-editing. The pack is DATA (\`game.json\`,
per-level \`score.json\` + GLB, audio beds) performed by the versioned
mojulo-godot kernel in \`kernel/\` (v${kernelVersion}) — one score, two
instruments; the web build is the reference performance.

## Provenance

- source ref: \`${ref}\`
- manifest sha256/16: \`${manifestHash}\`
- kernel: mojulo-godot ${kernelVersion}
- units: 1 mojulo unit = 1 meter; frames converted z-up → y-up by the kernel
- re-mint: \`${remint ?? `node scripts/export-godot.mjs --ref ${ref}`}\` (from mojulo's \`control/\`)

## Levels

${levelList}

## Play

Open in Godot ≥4.5 (or \`godot --path .\`). The menu lists the levels;
completing one returns you to the menu with the next gate unlocked.
Progress persists in \`user://progress.cfg\`. In a level: WASD/arrows +
mouse, Space jumps, Esc frees the mouse, M returns to the menu.

## What travelled, what didn't

${ledgerLines({ skipped_store: ledger.skipped_store, ...(ledger.skipped_shell ? { skipped_shell: ledger.skipped_shell } : {}), ...(ledger.gate_approximated ? { gate_approximated: ledger.gate_approximated } : {}) })}

${perLevelLedgers}
`,
  });

  return { files, ledger };
}
