/**
 * godot-arcade.js — the Godot leg for PIXELIZER games (2D reducer games).
 *
 * A pixelizer game is a pure step(state, action) reducer plus a skin; it has
 * no scene, so the 3D pack (godot-pack.js) refuses it. This is its own pack:
 * DATA (game.json, skin.json = bank tiles + legend, probe/replay.json, the
 * groove + SFX WAVs when music is on) performed by a SEPARATE versioned
 * kernel (godot-arcade-kernel/: arcade.gd the shell, <reducer>.gd a hand
 * port of the JS reducer). One reducer, two instruments; the web build is
 * the reference. The proof that the port IS the reducer is the replay
 * fixture — the export driver replays it headless and compares field by
 * field (brickster-replay.js).
 *
 * Deterministic: same row → same pack bytes. No dice, no timestamps.
 * Absent music ⇒ no audio files, zero bytes.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { SketchRepository } from '@/lib/db/repositories/sketches';
import { BANK, LEGEND } from '@/lib/graph/pixelizer/brickster-skin';
import { GROOVE, SFX } from '@/lib/graph/pixelizer/brickster-audio.recipe';
import { buildReplayFixture } from '@/lib/graph/pixelizer/brickster-replay';
import { manifestIdentity } from './engine-score.js';
import { writePack } from './godot-pack.js';

// reducer id → what the arcade kernel needs beyond the manifest. A reducer
// absent here has no GDScript port yet and refuses with a teaching error.
export const ARCADE_REDUCERS = {
  brickster: {
    skin: { register: '8bit', tileSize: [8, 8], background: '#0c0c14', bank: BANK, legend: LEGEND },
    music: GROOVE,
    sfx: SFX,
    replay: buildReplayFixture,
    cols: 12,
    rows: 22,
  },
};
export const ARCADE_REDUCER_IDS = Object.keys(ARCADE_REDUCERS);

const arcadeKernelDir = () => path.join(process.cwd(), 'lib', 'graph', 'scene', 'godot-arcade-kernel');
const hashOf = (m) => createHash('sha256').update(JSON.stringify(manifestIdentity(m))).digest('hex').slice(0, 16);
const gdName = (s) => String(s).replace(/[^A-Za-z0-9_]/g, '_');
const gdStr = (s) => JSON.stringify(String(s));
const SCALE = 4;
const TILE = 8;

export async function arcadeKernelVersion() {
  return (await fs.readFile(path.join(arcadeKernelDir(), 'VERSION'), 'utf8')).trim();
}

const ledgerLines = (ledger) => Object.entries(ledger)
  .map(([k, v]) => `- \`${k}\`${v.count != null ? ` ×${v.count}` : ''}${v.kinds ? ` (${v.kinds.join(', ')})` : ''} — ${v.note}`)
  .join('\n');

/**
 * emitGodotArcade — the text stubs of an arcade pack: project.godot (2D,
 * nearest filter, canvas_items stretch at the shell's native size), the
 * scene stub pointing kernel/arcade.gd at the data, presets, README ledger.
 * audio: { music: 'audio/groove.wav' | null, sfx: [cue ids] }.
 */
export function emitGodotArcade({ ref, title, reducer, manifestHash, kernelVersion = '?', audio = { music: null, sfx: [] }, cols = 12, rows = 22, remint = null }) {
  const width = 16 * 2 + cols * TILE * SCALE + 200;
  const height = rows * TILE * SCALE + 48;   // the well strip + the key line under it (arcade.gd)
  const ledger = {
    reducer_ported: { note: `kernel/${reducer}.gd is a hand port of the JS reducer; probe/replay.json is the parity proof (${'`'}godot --headless --path . -- --mojulo-replay=res://probe/replay.json${'`'})` },
    tempo_static: { note: 'the web shell re-lays the groove faster as the level climbs; the pack loops one bed at base tempo' },
    polka_absent: { note: 'the POLKA alternate track and the track toggle do not travel' },
    touch_pad_absent: { note: 'the knob + HOLD touch pad does not travel — keyboard only' },
  };
  if (audio.music) {
    ledger.music_carried = { note: `${audio.music} loops from the first key press; mute is the OS mixer` };
  } else {
    ledger.music_absent = { note: 'music:false — no audio files travel (zero bytes)' };
  }
  if (audio.sfx?.length) {
    ledger.sfx_carried = { count: audio.sfx.length, kinds: audio.sfx, note: 'cue WAVs under audio/sfx/, fired by the same rules as the web shell' };
  }
  const props = [`game_path = "res://game.json"`, `skin_path = "res://skin.json"`];
  if (audio.music) props.push(`music_path = "res://${audio.music}"`);
  if (audio.sfx?.length) props.push(`sfx_dir = "res://audio/sfx"`);
  const files = [
    {
      file: 'project.godot',
      text: `; generated by mojulo export-godot (arcade) — do not hand-edit; re-mint from recipe/
config_version=5

[application]

config/name=${gdStr(title)}
run/main_scene="res://arcade.tscn"

[display]

window/size/viewport_width=${width}
window/size/viewport_height=${height}
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

textures/canvas_textures/default_texture_filter=0
renderer/rendering_method.web="gl_compatibility"
`,
    },
    {
      file: 'arcade.tscn',
      text: `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://kernel/arcade.gd" id="kernel"]

[node name="Arcade" type="Node2D"]
script = ExtResource("kernel")
${props.join('\n')}
`,
    },
    {
      file: 'export_presets.cfg',
      text: `[preset.0]

name="Web"
platform="Web"
runnable=true
export_filter="all_resources"
include_filter="*.json"
export_path="build/web/index.html"

[preset.0.options]

variant/thread_support=false

[preset.1]

name="macOS"
platform="macOS"
runnable=true
export_filter="all_resources"
include_filter="*.json"
export_path="build/mac/${gdName(ref)}.zip"

[preset.1.options]

application/bundle_identifier="com.mojulo.${gdName(ref)}"
`,
    },
    { file: '.gitignore', text: '.godot/\nbuild/\n' },
    {
      file: 'README.md',
      text: `# ${title} — Godot handoff (arcade)

A generated Godot 4 pack (mojulo \`export-godot\`, arcade scope). The game's
truth lives in \`recipe/\` — this whole folder is a derived artifact; re-mint
it from the recipe rather than hand-editing. The pack is DATA (\`game.json\`,
\`skin.json\`, \`probe/replay.json\`, audio) performed by the versioned
mojulo-godot arcade kernel in \`kernel/\` (v${kernelVersion}): \`arcade.gd\` is the
shell, \`${reducer}.gd\` a hand port of the JS reducer. One reducer, two
instruments; the web build is the reference performance.

## Provenance

- source ref: \`${ref}\`
- manifest sha256/16: \`${manifestHash}\`
- kernel: mojulo-godot-arcade ${kernelVersion}
- reducer: \`${reducer}\`
- re-mint: \`${remint ?? `node scripts/export-godot.mjs --ref ${ref}`}\` (from mojulo's \`control/\`)

## Open and play

Open the folder in Godot ≥4.5 (or \`godot --path .\`) and run. Enter starts;
arrows move and soft-drop, Space hard-drops, Z/X/Up rotate, C or Shift holds,
Enter restarts after game over.

## Replay probe

\`probe/replay.json\` is a seeded action script with the JS reducer's outcome.
\`godot --headless --path . -- --mojulo-replay=res://probe/replay.json\` replays
it through \`kernel/${reducer}.gd\` and prints a \`[mojulo-replay]\` digest; the
export driver compares it field by field. A port that drifts fails there.

## What travelled, what didn't

${ledgerLines(ledger)}
`,
    },
  ];
  return { files, ledger };
}

/** A pixelizer game → data + arcade kernel pack at outDir. */
export async function buildGodotArcadePack({ ref, outDir, log = () => {} }) {
  const sketch = SketchRepository.getByRef(ref);
  if (!sketch) throw new Error(`sketch '${ref}' not found`);
  const manifest = sketch.manifest ?? {};
  if (manifest.engine !== 'pixelizer' || manifest.kind !== 'game') {
    throw new Error(`'${ref}' is not a pixelizer game (engine '${manifest.engine ?? 'none'}', kind '${manifest.kind ?? 'none'}')`);
  }
  const reducer = manifest.reducer;
  const def = ARCADE_REDUCERS[reducer];
  if (!def) {
    throw new Error(`'${ref}': reducer '${reducer}' has no Godot kernel yet — ${ARCADE_REDUCER_IDS.join(', ')} travel(s); `
      + 'a port is a hand-authored kernel/<reducer>.gd beside kernel/arcade.gd plus a replay fixture proving parity');
  }
  const version = await arcadeKernelVersion();
  const title = manifest.title ?? sketch.title ?? ref;
  const fixture = def.replay();
  const binaries = [
    { rel: 'game.json', bytes: JSON.stringify(manifest, null, 2) },
    { rel: 'skin.json', bytes: JSON.stringify(def.skin, null, 2) },
    { rel: 'probe/replay.json', bytes: JSON.stringify(fixture, null, 2) },
    { rel: `recipe/game.json`, bytes: JSON.stringify(manifest, null, 2) },
  ];
  const audio = { music: null, sfx: [] };
  if (manifest.music !== false) {
    const { renderBeatsOffline } = await import('@/lib/graph/beats/beats-render');
    const groove = await renderBeatsOffline(def.music, { loops: 2, tail: 0 });
    binaries.push({ rel: 'audio/groove.wav', bytes: groove.wav });
    audio.music = 'audio/groove.wav';
    log(`groove rendered — ${groove.wav.length} bytes`);
    const cues = Object.keys(def.sfx?.cues ?? {});
    for (const cue of cues) {
      const r = await renderBeatsOffline({ kind: 'beats-sfx', cues: def.sfx.cues }, { cue, tail: 0.5 });
      binaries.push({ rel: `audio/sfx/${cue}.wav`, bytes: r.wav });
    }
    audio.sfx = cues;
    if (cues.length) log(`${cues.length} sfx cues rendered`);
  }
  const emitted = emitGodotArcade({
    ref, title, reducer, manifestHash: hashOf(manifest), kernelVersion: version, audio,
    cols: def.cols, rows: def.rows, remint: `node scripts/export-godot.mjs --ref ${ref}`,
  });
  const written = await writePack({ outDir, binaries, emitted, portability: null, kernelSrc: arcadeKernelDir() });
  return {
    scope: 'arcade', ref, dir: outDir, manifestHash: hashOf(manifest), kernelVersion: version, reducer,
    written, ledger: emitted.ledger, portability: { portable: true, flags: [] }, sceneChecks: [],
    replay: { file: 'probe/replay.json', steps: fixture.steps, expected: fixture.expected },
  };
}
