/**
 * godot-project.js — the Godot 4 pack emitter (godot-handoff.plan.md G1 +
 * game scope, reshaped by G6: kernel architecture).
 *
 * Since kernel 0.1.0 the pack ships DATA and the versioned hand-authored
 * kernel (lib/graph/scene/godot-kernel/, copied in by the driver) performs
 * it: level.tscn is a three-line stub pointing kernel/level.gd at
 * score.json; game packs add game.json + a menu stub + the Game autoload
 * (kernel/game.gd). All promotion — ground, colliders, cameras, walker, the
 * full mechanics vocabulary, material fixup — happens in the kernel at
 * runtime. One score, two instruments: game-shell.js is the web kernel,
 * godot-kernel/ is this one.
 *
 * The emitter's remaining jobs: scene stubs, project.godot, export presets,
 * .gitignore, and the provenance README with the honest-loss ledger (which
 * shrank — the vocabulary is now interpreted, not ledgered). A rigged
 * layered figure's pack also takes the importer's settings for its skinned
 * GLB and figure.gd (FIGURE_VIEW_GD: the kernel's level extended, no walker).
 * Everything emitted is deterministic text: no dice, no timestamps, stable
 * ordering, no uids (path fallback, the plan's uid note).
 */

import { GREYBOX_HANDOFF_SENTENCE } from './engine-score.js';

const MECHANICS_VOCAB = ['reach-exit', 'collect', 'hazard-damage', 'fail-on-death', 'survive'];
const COMPLETION_KINDS = ['reach-exit', 'survive'];

/** The player entity's locomotion row, if the score has one — the seat is a
 * walking suit (third-person boom) rather than a first-person walker. */
const playerSuit = (score) => {
  const e = (score?.entities ?? []).find((x) => x?.id === score?.player);
  return e?.locomotion && (e.locomotion.idle || e.locomotion.walk) ? e.locomotion : null;
};

// The greybox seam (skin-over-mesh.plan.md): stamped packs carry the handoff
// sentence as its own README section; unstamped packs emit byte-identical text.
const greyboxSection = (stamped) => (stamped ? `## Greybox handoff

${GREYBOX_HANDOFF_SENTENCE}

` : '');

const fmt = (n) => {
  const v = Math.round(n * 1e6) / 1e6;
  return Object.is(v, -0) ? '0' : String(v);
};
const gdName = (s) => String(s).replace(/[^A-Za-z0-9_]/g, '_');
const gdStr = (s) => JSON.stringify(String(s));
const GITIGNORE = '.godot/\nbuild/\n';

// Godot 4 requires `exclude_filter` in every preset (without it the import logs one ERROR per preset); emitted with a
// figure only, so every other pack stays byte-identical.
function buildPresets(ref, { exclude = false } = {}) {
  const ex = exclude ? 'exclude_filter=""\n' : '';
  return `[preset.0]

name="Web"
platform="Web"
runnable=true
export_filter="all_resources"
include_filter="*.json"
${ex}export_path="build/web/index.html"

[preset.0.options]

variant/thread_support=false

[preset.1]

name="macOS"
platform="macOS"
runnable=true
export_filter="all_resources"
include_filter="*.json"
${ex}export_path="build/mac/${gdName(ref)}.zip"

[preset.1.options]

application/bundle_identifier="com.mojulo.${gdName(ref)}"
`;
}

function buildProjectGodot({ title, mainScene, autoloadGame = false }) {
  return `; generated by mojulo export-godot — do not hand-edit; re-mint from recipe/
config_version=5

[application]

config/name=${gdStr(title)}
run/main_scene="res://${mainScene}"
${autoloadGame ? `
[autoload]

Game="*res://kernel/game.gd"
` : ''}
[rendering]

renderer/rendering_method.web="gl_compatibility"
`;
}

const ledgerLines = (ledger) => Object.entries(ledger)
  .map(([k, v]) => `- \`${k}\`${v.count != null ? ` ×${v.count}` : ''}${v.kinds ? ` (${v.kinds.join(', ')})` : ''} — ${v.note}`)
  .join('\n');

/** The per-level scene stub: kernel/level.gd pointed at the level's data — or, for a rigged layered figure, figure.gd
 * (the kernel's level extended) with the clip it plays and the view that frames it. */
function levelStub({ resBase = '', glbFile = 'model.glb', musicPath = null, musicDb = null, figure = null }) {
  const props = [`score_path = "res://${resBase}score.json"`];
  if (musicPath) props.push(`music_path = "res://${musicPath}"`);
  if (musicDb != null) props.push(`music_db = ${fmt(musicDb)}`);
  if (figure) props.push(`clip = ${gdStr(`${figure.name}:${figure.clip}`)}`, `view = ${figure.view}`);
  const script = figure ? { path: `${resBase}figure.gd`, id: 'figure' } : { path: 'kernel/level.gd', id: 'kernel' };
  return `[gd_scene load_steps=3 format=3]

[ext_resource type="PackedScene" path="res://${resBase}${glbFile}" id="model"]
[ext_resource type="Script" path="res://${script.path}" id="${script.id}"]

[node name="Level" type="Node3D"]
script = ExtResource("${script.id}")
${props.join('\n')}

[node name="World" parent="." instance=ExtResource("model")]
`;
}

/** The honest-loss ledger for one level, post-kernel: the vocabulary is
 * interpreted now; only out-of-vocabulary gameplay and non-geometry channels
 * remain losses. */
function levelLedger(score, { gameMode = false } = {}) {
  const ledger = { ...score.ledger };
  // skin-over-mesh phase 3: surface/atlas textures are a CARRIED line, not a
  // loss — they ride the GLB (TEXCOORD_0 + embedded PNG); Godot's importer
  // maps them to albedo_texture and the kernel fixup's vertex-colour albedo
  // MULTIPLIES with them, matching the web renderer's texel × baked light.
  if (Array.isArray(score.textures) && score.textures.length) {
    ledger.textures_carried = {
      count: score.textures.length,
      kinds: score.textures,
      note: 'surface/atlas textures travel inside the GLB and multiply with the baked vertex colours (kernel material fixup) — the web build is the reference look',
    };
  }
  ledger.entity_markers = {
    note: 'entities that baked no mesh (glyph/primitive bodies — export-side gap) render as gold placeholder markers; the web build is the reference look',
  };
  ledger.web_color_shift = {
    note: 'web preset renders via GL Compatibility, which reads vertex colours as sRGB — linear COLOR_0 draws darker there; desktop uses Forward+ and is colour-true',
  };
  if (score.ground != null) {
    ledger.promoted_ground = { note: 'implicit runtime ground plane promoted by the kernel — the collider AABBs are obstacle hulls only, never the floor' };
  }
  // walking-suit-backport.md G-L1..G-L5: the locomotion row is PERFORMED —
  // first-claimant figures play their idle, the player's figure walks as a
  // third-person suit. Absent rows ⇒ no line, byte-identical ledger.
  const rows = (score.entities ?? []).filter((e) => e?.locomotion && (e.locomotion.idle || e.locomotion.walk));
  if (rows.length) {
    ledger.locomotion_performed = {
      count: rows.length,
      note: `idle/walk clips performed live by kernel/level.gd (one AnimationPlayer per figure over the GLB's own clips)${playerSuit(score) ? '; the player figure follows the walker as a third-person suit on a SpringArm3D, framed from its own height' : ''}`,
    };
  }
  const kinds = (score.mechanics ?? []).map((m) => m?.kind).filter(Boolean);
  const interpreted = kinds.filter((k) => MECHANICS_VOCAB.includes(k));
  const unknown = kinds.filter((k) => !MECHANICS_VOCAB.includes(k));
  if (interpreted.length) {
    ledger.interpreted_mechanics = { count: interpreted.length, kinds: [...new Set(interpreted)], note: 'performed live by kernel/level.gd' };
  }
  if (unknown.length) {
    ledger.unknown_mechanics = { count: unknown.length, kinds: [...new Set(unknown)], note: 'outside the kernel vocabulary — do not travel' };
  }
  if (gameMode && !kinds.some((k) => COMPLETION_KINDS.includes(k))) {
    ledger.no_completion_path = {
      note: 'no completion mechanic — the authored win condition lives in the runtime, which does not travel; the level is an explorable arena (M returns to the menu)',
    };
  }
  return ledger;
}

/** The importer's settings for a rigged layered figure's skinned GLB (`<glb>.import`): no LOD generation (by default
 * Godot builds up to six LODs of the skinned surface), and mesh compression off — Godot never compresses a skinned
 * surface, so that one keeps the static meshes whole once they carry normals and tangents. Godot rewrites the file on
 * import (uid, path, every param); the pack ships only what differs from the defaults. */
export const FIGURE_IMPORT = `[remap]

importer="scene"
importer_version=1
type="PackedScene"

[params]

meshes/generate_lods=false
meshes/force_disable_compression=true
`;

/** A rigged layered figure's scene script (figure.gd at the pack root): the kernel's level — its material, rim and light
 * contracts — with no walker spawned over the figure, playing one clip on a loop under one authored view. It reaches
 * the kernel's _spawn_walker, _imported_player, _anim_name and _play_loop, so a kernel that renames them breaks it. */
export const FIGURE_VIEW_GD = `extends "res://kernel/level.gd"
# mojulo figure view — emitted beside the kernel for a rigged layered figure's pack
# (godot-project.js): the kernel's level, its material, rim and light contracts
# kept, with no walker; the figure plays \`clip\` (the GLB's clip name) on a loop
# and the authored view \`view\` (an index into score.json cameras) frames it.

@export var clip: String = ""
@export var view: int = 0


func _spawn_walker() -> void:
\tpass


func _ready() -> void:
\tsuper()
\tvar p := _imported_player()
\tvar anim := _anim_name(p, clip) if p != null else ""
\tif anim != "":
\t\t_play_loop(p, anim)
\tvar cam := get_node_or_null("View%d" % view) as Camera3D
\tif cam != null:
\t\tcam.make_current()
`;

/** The figure's ledger rows: what the skinned figure carries and plays, and what it does not carry yet. */
const figureLedger = (f) => ({
  figure_skinned: {
    note: `one skinned mesh (${f.joints} joints) carrying its ${f.clips.length} clips, one second each — the GLB export_model { clips: '_all', skinned: true } writes (lit: true under --lit); level.tscn plays '${f.clip}' on a loop under the authored ${f.viewName} view, which frames the figure at rest, with no walker (figure.gd extends the kernel's level); model.glb.import turns LOD generation off (and mesh compression, which Godot never puts on a skinned surface)`,
  },
  figure_normals: { note: 'the skinned mesh carries no NORMAL or TANGENT yet: the default export travels as its baked look, unlit, and under --lit an engine light has no normals to shade it with' },
});

/** The README's "Open and play" for a figure's pack. */
const figurePlay = (f) => `Open the folder in Godot ≥4.5 (or \`godot --path .\`) and run: the figure plays
\`${f.clip}\` on a loop under the authored ${f.viewName} view, which frames it at
rest (a clip that reaches overhead can leave the frame).${f.clips.includes('gesture') && f.clip !== 'gesture' ? `
\`${f.clip}\` is the figure's own loop, not the stand the World page opens on
(the clip \`gesture\`).` : ''} It is one skinned mesh
(${f.joints} joints) carrying its ${f.clips.length} clips (${f.clips.map((c) => `\`${c}\``).join(', ')}) on the
imported AnimationPlayer as \`${f.name}_<clip>\`, one second each (the World
page plays a clip over three): set \`clip\` (\`${f.name}:<clip>\`) and \`view\`
(an index into the score's cameras) on the \`Level\` node of \`level.tscn\` to
play another. \`model.glb.import\` imports it with LOD generation off.`;

/**
 * emitGodotProject — a standalone world pack: stub + shell + README.
 * The driver ships kernel/, model.glb, score.json, recipe/, audio/.
 * `figure` ({ name, clip, clips, view, viewName, joints }, godot-pack.js): a
 * rigged layered figure's pack — its scene plays the clip under the view, and
 * the pack gains model.glb.import and figure.gd; absent, every file as before.
 */
export function emitGodotProject({ ref, score, manifestHash, glbFile = 'model.glb', audioFile = null, kernelVersion = '?', remint = null, figure = null }) {
  const title = score.title ?? ref;
  const ledger = figure ? { ...levelLedger(score), ...figureLedger(figure) } : levelLedger(score);
  const files = [
    { file: 'project.godot', text: buildProjectGodot({ title, mainScene: 'level.tscn' }) },
    { file: 'level.tscn', text: levelStub({ glbFile, musicPath: audioFile, figure }) },
    { file: 'export_presets.cfg', text: buildPresets(ref, { exclude: !!figure }) },
    { file: '.gitignore', text: GITIGNORE },
    {
      file: 'README.md',
      text: `# ${title} — Godot handoff

A generated Godot 4 pack (mojulo \`export-godot\`). The world's truth lives
in \`recipe/\` — this whole folder is a derived artifact; re-mint it from the
recipe rather than hand-editing. The pack is DATA (\`score.json\`, the GLB,
audio) performed by the versioned mojulo-godot kernel in \`kernel/\`
(v${kernelVersion}) — one score, two instruments; the web build is the
reference performance.

## Provenance

- source ref: \`${ref}\`
- manifest sha256/16: \`${manifestHash}\`
- kernel: mojulo-godot ${kernelVersion}
- units: ${score.units}; frame converted z-up → y-up by the kernel, matching the GLB root
- re-mint: \`${remint ?? `node scripts/export-godot.mjs --ref ${ref}`}\` (from mojulo's \`control/\`)

${greyboxSection(score.posture === 'greybox')}## Open and play

${figure ? figurePlay(figure) : `Open the folder in Godot ≥4.5 (or \`godot --path .\`) and run. WASD/arrows to
walk, mouse to look, Space jumps, Esc frees the mouse${score.cameras?.length ? ', 0 toggles the authored camera framing' : ''}.${playerSuit(score) ? `
Your figure is a rigged body: it follows you as a third-person suit (walk
cycle while moving, idle when still), and every other rigged figure breathes
its idle. Headless motion probe: \`godot --headless --path . res://level.tscn -- --mojulo-autowalk --mojulo-frames=120\`.` : ''}`}

## What travelled, what didn't

${ledgerLines(ledger)}
`,
    },
    ...(figure ? [{ file: `${glbFile}.import`, text: FIGURE_IMPORT }, { file: 'figure.gd', text: FIGURE_VIEW_GD }] : []),
  ];
  return { files, ledger };
}

/**
 * emitGodotGame — a game pack: per-level stubs + menu stub + shell + README.
 * The driver ships kernel/, game.json, per-level model.glb/score.json,
 * recipe/, audio/. levels: [{ ref, title, gate, score, audioFile, audioDb }].
 */
export function emitGodotGame({ ref, title, manifestHash, levels, music = {}, shellExtras = [], kernelVersion = '?', remint = null }) {
  const files = [];
  const ledger = {
    skipped_store: { note: 'store slices (character/inventory state) do not travel — only completion progression is kept (user://progress.cfg)' },
    levels: {},
  };
  if (shellExtras.length) {
    ledger.skipped_shell = {
      kinds: shellExtras,
      note: 'authored shell UI beyond the level list (menu structure, setup/hangar, difficulty, theme) does not travel — the kernel menu is a plain level table',
    };
  }
  const oddGates = levels.filter((lv) => lv.gate && !lv.gate.completed);
  if (oddGates.length) {
    ledger.gate_approximated = {
      count: oddGates.length,
      note: 'non-completion gates (store flags) approximated as unlocked — flag state does not travel',
    };
  }

  for (const lv of levels) {
    files.push({
      file: `levels/${lv.ref}/level.tscn`,
      text: levelStub({ resBase: `levels/${lv.ref}/`, musicPath: lv.audioFile ?? null, musicDb: lv.audioDb ?? null }),
    });
    ledger.levels[lv.ref] = levelLedger(lv.score, { gameMode: true });
  }

  const menuExt = [`[ext_resource type="Script" path="res://kernel/menu.gd" id="menu_gd"]`];
  if (music.menuFile) menuExt.push(`[ext_resource type="AudioStream" path="res://${music.menuFile}" id="music"]`);
  files.push({
    file: 'menu.tscn',
    text: `[gd_scene load_steps=${menuExt.length + 1} format=3]

${menuExt.join('\n')}

[node name="Menu" type="Control"]
anchor_right = 1.0
anchor_bottom = 1.0
script = ExtResource("menu_gd")
${music.menuFile ? `
[node name="Music" type="AudioStreamPlayer" parent="."]${music.menuDb != null ? `\nvolume_db = ${fmt(music.menuDb)}` : ''}\nstream = ExtResource("music")\n` : ''}`,
  });

  files.push({ file: 'project.godot', text: buildProjectGodot({ title, mainScene: 'menu.tscn', autoloadGame: true }) });
  files.push({ file: 'export_presets.cfg', text: buildPresets(ref) });
  files.push({ file: '.gitignore', text: GITIGNORE });

  const levelList = levels
    .map((lv, i) => `${i + 1}. ${lv.title ?? lv.ref} (\`${lv.ref}\`)${lv.gate?.completed ? ` — unlocks after \`${lv.gate.completed}\`` : ''}`)
    .join('\n');
  const perLevelLedgers = levels
    .map((lv) => `### \`${lv.ref}\`\n\n${ledgerLines(ledger.levels[lv.ref])}`)
    .join('\n\n');
  files.push({
    file: 'README.md',
    text: `# ${title} — Godot handoff (game)

A generated Godot 4 pack (mojulo \`export-godot\`, game scope). The game's
truth lives in \`recipe/\` — this whole folder is a derived artifact; re-mint
it from the recipe rather than hand-editing. The pack is DATA (\`game.json\`,
per-level \`score.json\` + GLB, audio beds) performed by the versioned
mojulo-godot kernel in \`kernel/\` (v${kernelVersion}) — one score, two
instruments; the web build is the reference performance.

## Provenance

- source ref: \`${ref}\`
- manifest sha256/16: \`${manifestHash}\`
- kernel: mojulo-godot ${kernelVersion}
- units: 1 mojulo unit = 1 meter; frames converted z-up → y-up by the kernel
- re-mint: \`${remint ?? `node scripts/export-godot.mjs --ref ${ref}`}\` (from mojulo's \`control/\`)

${greyboxSection(levels.some((lv) => lv.score?.posture === 'greybox'))}## Levels

${levelList}

## Play

Open in Godot ≥4.5 (or \`godot --path .\`). The menu lists the levels;
completing one returns you to the menu with the next gate unlocked.
Progress persists in \`user://progress.cfg\`. In a level: WASD/arrows +
mouse, Space jumps, Esc frees the mouse, M returns to the menu.${levels.some((lv) => playerSuit(lv.score)) ? `
Levels whose player is a rigged figure show it as a third-person suit that
follows you (walk cycle while moving, idle when still); other rigged figures
breathe their idle.` : ''}

## What travelled, what didn't

${ledgerLines({ skipped_store: ledger.skipped_store, ...(ledger.skipped_shell ? { skipped_shell: ledger.skipped_shell } : {}), ...(ledger.gate_approximated ? { gate_approximated: ledger.gate_approximated } : {}) })}

${perLevelLedgers}
`,
  });

  return { files, ledger };
}
