import { describe, expect, it } from 'vitest';

import { findSlicer, parseDuration, parseGcodeHeader, parseSlicerInfo, summarizePrintGate } from './print-gate.js';

describe('findSlicer', () => {
  it('honours MOJULO_SLICER and guesses the family from the path', () => {
    expect(findSlicer({ env: { MOJULO_SLICER: '/opt/PrusaSlicer/prusa-slicer' } })).toEqual({ id: 'prusa', family: 'prusa', bin: '/opt/PrusaSlicer/prusa-slicer' });
    expect(findSlicer({ env: { MOJULO_SLICER: '/x/OrcaSlicer' } }).family).toBe('orca');
    expect(findSlicer({ env: { MOJULO_SLICER: '/x/myslicer' } })).toEqual({ id: 'custom', family: 'prusa', bin: '/x/myslicer' });
  });

  it('walks PATH names before app bundles, in candidate order', () => {
    const which = (n) => (n === 'superslicer' ? '/usr/local/bin/superslicer' : null);
    expect(findSlicer({ which })).toEqual({ id: 'superslicer', family: 'prusa', bin: '/usr/local/bin/superslicer' });
    const exists = (p) => p === '/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
    expect(findSlicer({ exists }).id).toBe('orca');
    expect(findSlicer({})).toBeNull();
  });
});

describe('parsers', () => {
  it('reads PrusaSlicer --info', () => {
    const info = parseSlicerInfo(`[model.3mf]
size_x = 40.000
size_y = 40.000
size_z = 60.000
min_x = 0
number_of_facets = 128
manifold = yes
number_of_parts = 1
volume = 75398.22
`);
    expect(info).toEqual({ size_mm: [40, 40, 60], volume_mm3: 75398.22, facets: 128, parts: 1, manifold: true });
    expect(parseSlicerInfo('').manifold).toBeNull();
  });

  it('reads durations', () => {
    expect(parseDuration('1h 23m 45s')).toBe(5025);
    expect(parseDuration('2d 1m')).toBe(172860);
    expect(parseDuration('nope')).toBeNull();
  });

  it('reads the G-code comment ledger, tolerating absent fields', () => {
    const g = parseGcodeHeader(`; generated by PrusaSlicer 2.8.0
;LAYER_CHANGE
G1 X1
;LAYER_CHANGE
; filament used [mm] = 1234.50
; filament used [cm3] = 2.97
; filament used [g] = 3.68
; total filament used [g] = 3.68
; filament cost = 0.07
; estimated printing time (normal mode) = 1h 2m 3s
; layer_height = 0.2
; support_material = 1
`);
    expect(g).toEqual({ print_time_s: 3723, filament_mm: 1234.5, filament_cm3: 2.97, filament_g: 3.68, filament_cost: 0.07, layer_height_mm: 0.2, supports: true, layers: 2 });
    const empty = parseGcodeHeader('G1 X0');
    expect(empty.print_time_s).toBeNull();
    expect(empty.supports).toBeNull();
    expect(empty.layers).toBeNull();
  });

  it('summarizes: size agreement catches a unit slip', () => {
    const info = { size_mm: [40, 40, 60], manifold: true, parts: 1, volume_mm3: 1 };
    const ok = summarizePrintGate({ info, gcode: { print_time_s: 10, filament_g: 1 }, exportSizeMm: [40, 40, 60] });
    expect(ok.sliced).toBe(true);
    expect(ok.size_agrees).toBe(true);
    const slip = summarizePrintGate({ info, gcode: null, exportSizeMm: [4, 4, 6] });
    expect(slip.sliced).toBe(false);
    expect(slip.size_agrees).toBe(false);
    expect(summarizePrintGate({}).size_agrees).toBeNull();
  });
});
