import { describe, expect, it } from 'vitest';

import { DEFAULT_BED_CENTER, bedCenterFromProfile, findSlicer, manifoldNote, parseDuration, parseGcodeHeader, parseSlicerInfo, sliceFailureReason, summarizePrintGate, orcaProfileFiles, orcaSliceArgs, parseOrcaGcodeHeader } from './print-gate.js';

// text-to-cad-seam.plan.md T6 — the orca family (OrcaSlicer / Bambu Studio): JSON profiles,
// no defaults, arranged onto the bed, its own G-code ledger keys. Flags per the Bambu Studio
// CLI wiki; unverified against a real install here, so these pin the SHAPE, not a run.
describe('orca family', () => {
  it('orcaProfileFiles wants a machine + process pair, from a ;-list or a directory', () => {
    expect(orcaProfileFiles('m/machine.json;m/process.json;m/filament_pla.json')).toEqual({ machine: 'm/machine.json', process: 'm/process.json', filaments: ['m/filament_pla.json'] });
    expect(orcaProfileFiles('m/machine.json')).toBeNull();
    const listDir = (d) => (d === '/p' ? ['X1C machine.json', 'standard process.json', 'filament A.json', 'filament B.json', 'notes.txt'] : null);
    expect(orcaProfileFiles('/p', { listDir })).toEqual({ machine: '/p/X1C machine.json', process: '/p/standard process.json', filaments: ['/p/filament A.json', '/p/filament B.json'] });
    expect(orcaProfileFiles(null)).toBeNull();
  });

  it('orcaSliceArgs arranges the whole plate and exports the project + slice data into the outcome dir', () => {
    const a = orcaSliceArgs({ file: '/o/model.3mf', outDir: '/o', profiles: { machine: 'm.json', process: 'p.json', filaments: ['f.json'] }, supports: true });
    expect(a).toEqual(['--load-settings', 'm.json;p.json', '--load-filaments', 'f.json', '--slice', '0', '--arrange', '1', '--enable-support', '--debug', '2', '--export-3mf', 'sliced.3mf', '--export-slicedata', '/o/slicedata', '--outputdir', '/o', '/o/model.3mf']);
    expect(() => orcaSliceArgs({ file: 'x', outDir: 'y', profiles: { machine: 'm.json' } })).toThrow(/machine \+ process/);
  });

  it('parseOrcaGcodeHeader reads the Bambu / Orca ledger keys, nulls for the rest', () => {
    const g = parseOrcaGcodeHeader(`; HEADER_BLOCK_START
; BambuStudio 01.09.00.70
; model printing time: 45m 12s; total estimated time: 50m 3s
; total layer number: 110
; total filament length [mm] : 4114.68
; total filament weight [g] : 12.27
; filament_density: 1.24
; layer_height = 0.2
; enable_support = 0
`);
    expect(g).toEqual({ print_time_s: 3003, filament_mm: 4114.68, filament_cm3: null, filament_g: 12.27, filament_cost: null, layer_height_mm: 0.2, supports: false, layers: 110 });
    expect(parseOrcaGcodeHeader('').print_time_s).toBeNull();
    // summarizePrintGate treats it like any G-code ledger; no --info twin ⇒ size_agrees null
    const s = summarizePrintGate({ info: null, gcode: g, exportSizeMm: [81, 30, 33] });
    expect(s.sliced).toBe(true);
    expect(s.size_agrees).toBeNull();
    expect(s.print_time_s).toBe(3003);
  });
});

describe('findSlicer', () => {
  it('honours MOJULO_SLICER and guesses the family from the path', () => {
    expect(findSlicer({ env: { MOJULO_SLICER: '/opt/PrusaSlicer/prusa-slicer' } })).toEqual({ id: 'prusa', family: 'prusa', bin: '/opt/PrusaSlicer/prusa-slicer' });
    expect(findSlicer({ env: { MOJULO_SLICER: '/x/OrcaSlicer' } }).family).toBe('orca');
    expect(findSlicer({ env: { MOJULO_SLICER: '/x/myslicer' } })).toEqual({ id: 'custom', family: 'prusa', bin: '/x/myslicer' });
  });

  it('walks PATH names before app bundles, in candidate order', () => {
    const which = (n) => (n === 'superslicer' ? '/usr/local/bin/superslicer' : null);
    expect(findSlicer({ which })).toEqual({ id: 'superslicer', family: 'prusa', bin: '/usr/local/bin/superslicer' });
    const exists = (p) => p === '/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
    expect(findSlicer({ exists }).id).toBe('orca');
    expect(findSlicer({})).toBeNull();
  });
});

describe('parsers', () => {
  it('reads PrusaSlicer --info', () => {
    const info = parseSlicerInfo(`[model.3mf]
size_x = 40.000
size_y = 40.000
size_z = 60.000
min_x = 0
number_of_facets = 128
manifold = yes
number_of_parts = 1
volume = 75398.22
`);
    expect(info).toEqual({ size_mm: [40, 40, 60], volume_mm3: 75398.22, facets: 128, parts: 1, manifold: true });
    expect(parseSlicerInfo('').manifold).toBeNull();
  });

  it('reads durations', () => {
    expect(parseDuration('1h 23m 45s')).toBe(5025);
    expect(parseDuration('2d 1m')).toBe(172860);
    expect(parseDuration('nope')).toBeNull();
  });

  it('reads the G-code comment ledger, tolerating absent fields', () => {
    const g = parseGcodeHeader(`; generated by PrusaSlicer 2.8.0
;LAYER_CHANGE
G1 X1
;LAYER_CHANGE
; filament used [mm] = 1234.50
; filament used [cm3] = 2.97
; filament used [g] = 3.68
; total filament used [g] = 3.68
; filament cost = 0.07
; estimated printing time (normal mode) = 1h 2m 3s
; layer_height = 0.2
; support_material = 1
`);
    expect(g).toEqual({ print_time_s: 3723, filament_mm: 1234.5, filament_cm3: 2.97, filament_g: 3.68, filament_cost: 0.07, layer_height_mm: 0.2, supports: true, layers: 2 });
    const empty = parseGcodeHeader('G1 X0');
    expect(empty.print_time_s).toBeNull();
    expect(empty.supports).toBeNull();
    expect(empty.layers).toBeNull();
  });

  it('summarizes: size agreement catches a unit slip', () => {
    const info = { size_mm: [40, 40, 60], manifold: true, parts: 1, volume_mm3: 1 };
    const ok = summarizePrintGate({ info, gcode: { print_time_s: 10, filament_g: 1 }, exportSizeMm: [40, 40, 60] });
    expect(ok.sliced).toBe(true);
    expect(ok.size_agrees).toBe(true);
    const slip = summarizePrintGate({ info, gcode: null, exportSizeMm: [4, 4, 6] });
    expect(slip.sliced).toBe(false);
    expect(slip.size_agrees).toBe(false);
    expect(summarizePrintGate({}).size_agrees).toBeNull();
  });
});

describe('placement + failure reasons (interchange-next N2)', () => {
  it('reads the bed centre from a profile, else null', () => {
    expect(bedCenterFromProfile('layer_height = 0.2\nbed_shape = 0x0,250x0,250x210,0x210\n')).toEqual([125, 105]);
    expect(bedCenterFromProfile('bed_shape = -50x-50,50x-50,50x50,-50x50')).toEqual([0, 0]);
    expect(bedCenterFromProfile('layer_height = 0.2')).toBeNull();
    expect(bedCenterFromProfile('bed_shape = garbage')).toBeNull();
    expect(DEFAULT_BED_CENTER).toEqual([100, 100]);
  });
  it('names the failures it knows and stays null otherwise', () => {
    expect(sliceFailureReason('All objects are outside of the print volume.')).toBe('outside_print_volume');
    expect(sliceFailureReason('Error: failed to load model.3mf')).toBe('file_not_read');
    expect(sliceFailureReason('89 => Calculating overhanging perimeters')).toBeNull();
    expect(sliceFailureReason('')).toBeNull();
  });
});

// text-to-cad-seam.plan.md T6, run 2026-09-08: Bambu Studio 02.08.02 on the hook 3MF with the
// app-bundle A1 system profiles. The header below is the real plate_1.gcode head.
describe('orca family — as Bambu Studio actually writes it', () => {
  const HEAD = `; HEADER_BLOCK_START
; BambuStudio 02.08.02.61
; model printing time: 1h 15m 18s; total estimated time: 1h 15m 19s
; total layer number: 165
; total filament length [mm] : 3311.14
; total filament volume [cm^3] : 7964.23
; total filament weight [g] : 0.00
; filament_density: 0
; filament_diameter: 1.75
; max_z_height: 33.00
; filament: 1
; support_material_on_wipe_tower: 0
; HEADER_BLOCK_END

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; enable_support = 0
; enable_support_ironing = 0
; layer_height = 0.2
; nozzle_diameter = 0.4
; printer_model = Bambu Lab A1
; support_air_filtration = 0
; support_angle = 0
; CONFIG_BLOCK_END
`;
  it('parseOrcaGcodeHeader reads the real Bambu header (time, layers, mm, cm^3, g, supports, layer height)', () => {
    expect(parseOrcaGcodeHeader(HEAD)).toEqual({
      print_time_s: 3600 + 15 * 60 + 19, filament_mm: 3311.14, filament_cm3: 7964.23, filament_g: 0, filament_cost: null, layer_height_mm: 0.2, supports: false, layers: 165,
    });
  });
  it('Bambu --info prints the PrusaSlicer block, so the size check is real for this family', () => {
    const info = parseSlicerInfo('[2026-09-08 22:17:19] [trace] Initializing StaticPrintConfigs\nsize_x = 81.000000\nsize_y = 30.000000\nsize_z = 33.000000\nmin_x = -40.500000\nnumber_of_facets = 316\nmanifold = yes\nnumber_of_parts =  2\nvolume = 16557.009766\n');
    expect(info).toEqual({ size_mm: [81, 30, 33], volume_mm3: 16557.009766, facets: 316, parts: 2, manifold: true });
    expect(summarizePrintGate({ info, gcode: parseOrcaGcodeHeader(HEAD), exportSizeMm: [81, 30, 33] })).toMatchObject({ sliced: true, size_agrees: true, manifold: true, parts: 2, layers: 165, print_time_s: 4519, supports: false });
  });
  it("orcaProfileFiles takes role=file entries, since Bambu's own profile names say the printer, not the role", () => {
    const p = orcaProfileFiles('machine=/A/Bambu Lab A1 0.4 nozzle.json;process=/A/0.20mm Standard @BBL A1.json;filament=/A/Bambu PLA Basic @BBL A1.json');
    expect(p).toEqual({ machine: '/A/Bambu Lab A1 0.4 nozzle.json', process: '/A/0.20mm Standard @BBL A1.json', filaments: ['/A/Bambu PLA Basic @BBL A1.json'] });
    expect(orcaProfileFiles('machine=/A/m.json')).toBeNull();
    expect(orcaProfileFiles('process=/A/p.json;machine=/A/m.json;filament=/A/f1.json;filament=/A/f2.json').filaments).toEqual(['/A/f1.json', '/A/f2.json']);
    // the bare list is unchanged
    expect(orcaProfileFiles('m/machine.json;m/process.json')).toEqual({ machine: 'm/machine.json', process: 'm/process.json', filaments: [] });
  });
  it('orcaSliceArgs puts a scratch --datadir first when the driver hands one', () => {
    const a = orcaSliceArgs({ file: '/o/model.3mf', outDir: '/o', profiles: { machine: 'm.json', process: 'p.json', filaments: [] }, datadir: '/tmp/dd', debug: 1 });
    expect(a.slice(0, 4)).toEqual(['--datadir', '/tmp/dd', '--load-settings', 'm.json;p.json']);
    expect(a).toContain('--debug');
    expect(a[a.indexOf('--debug') + 1]).toBe('1');
    expect(orcaSliceArgs({ file: 'x', outDir: 'y', profiles: { machine: 'm', process: 'p' } })[0]).toBe('--load-settings');
  });
  it('findSlicer names Bambu Studio from an explicit path, the way the driver reads --slicer', () => {
    expect(findSlicer({ env: { MOJULO_SLICER: '/Applications/BambuStudio.app/Contents/MacOS/BambuStudio' } })).toEqual({ id: 'bambu', family: 'orca', bin: '/Applications/BambuStudio.app/Contents/MacOS/BambuStudio' });
  });
});

// launch-falls-short.plan.md P3 — one truth about manifoldness: the stamp explains a slicer
// `manifold: false` by what actually shipped.
describe('manifoldNote', () => {
  it('is silent unless the slicer said false', () => {
    expect(manifoldNote({ manifold: true, parts: 1 })).toBeNull();
    expect(manifoldNote({ manifold: null })).toBeNull();
  });
  it('names the multi-shell case when no union shipped', () => {
    expect(manifoldNote({ manifold: false, parts: 2, union: null })).toMatch(/2 separate closed shells.*union not requested.*union: true/);
    expect(manifoldNote({ manifold: false, parts: 2, union: { applied: false, reason: 'manifold-3d not installed' } })).toMatch(/union not applied: manifold-3d not installed/);
  });
  it('points at a real open edge when the union did ship', () => {
    expect(manifoldNote({ manifold: false, parts: 1, union: { applied: true } })).toMatch(/unioned solid \(1 part\).*real open edge/);
  });
});
