/**
 * unreal-kernel.js — the mojulo-unreal kernel emitter (export-unreal.plan.md
 * rev 2 §1, U1).
 *
 * The runtime half of the instrument: a pack-carried CODE PLUGIN
 * (`MojuloKernel/`, copied to `<Project>/Plugins/`) that the operator's
 * project compiles itself — the direct sibling of Unity's `Runtime/*.cs` and
 * the Godot `godot-kernel/`. The kernel-language decision (U1): emitted C++
 * source, NOT Python-built Blueprint assets — Blueprints are opaque binary
 * .uassets (non-diffable, non-deterministic); a plugin is deterministic text,
 * name-independent (no .uproject Modules edit, no Target.cs), and drops into
 * a Blueprint-template project (UE prompts to compile on open).
 *
 * Semantics mirror the Unity kernel file-for-file:
 *   MojuloScore.*        <- (new) score/game.json readers + the C++ P()
 *   MojuloWalker.*       <- Runtime/MojuloWalker.cs (first-person walker)
 *   MojuloGameMode.*     <- Runtime/MojuloLevel.cs + MojuloGame.cs
 *   MojuloMenuGameMode.* <- Runtime/MojuloMenu.cs (+ its HUD)
 *   MojuloHUD.*          <- the OnGUI HUD (canvas DrawText is the analogue)
 * Progression: `Saved/mojulo.completed`, |-joined refs — the PlayerPrefs
 * key's semantics, a plain file instead of a platform registry.
 *
 * TWO implementations of the frame map exist on the Unreal leg (python for
 * import-time actors, C++ for runtime mechanics) — they MUST stay identical:
 * P(v) = (x*100, -y*100, z*100). The gate's frame_landmark pins python's;
 * the kernel's spawn/zone positions ride the same numbers.
 *
 * Everything here is deterministic text: no dice, no timestamps.
 */

const HEADER_CPP = '// generated by mojulo export-unreal — do not hand-edit; re-mint from recipe/\n';

/* ------------------------------------------------------------- plugin --- */

const uplugin = () => `${'{'}
  "FileVersion": 3,
  "FriendlyName": "Mojulo Kernel",
  "Description": "Performs a mojulo game score: walker, mechanics vocabulary, HUD, menu, music beds, progression. Generated by mojulo export-unreal; re-mint from the pack recipe.",
  "Category": "Mojulo",
  "CanContainContent": false,
  "EnabledByDefault": true,
  "Modules": [
    { "Name": "MojuloKernel", "Type": "Runtime", "LoadingPhase": "Default" }
  ]
${'}'}
`;

const buildCs = () => `${HEADER_CPP}using UnrealBuildTool;

public class MojuloKernel : ModuleRules
{
    public MojuloKernel(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "Json", "AssetRegistry", "LevelSequence", "MovieScene" });
    }
}
`;

const moduleCpp = () => `${HEADER_CPP}#include "Modules/ModuleManager.h"

IMPLEMENT_MODULE(FDefaultModuleImpl, MojuloKernel);
`;

/* -------------------------------------------------------------- score --- */

const scoreH = () => `${HEADER_CPP}// MojuloScore — score.json / game.json readers + the C++ half of the frame
// map. Mirrors the [Serializable] score classes in Unity's MojuloLevel.cs.
#pragma once

#include "CoreMinimal.h"

class AMojuloMarker;

struct FMojuloZone
{
    FVector Pos = FVector::ZeroVector;   // UE cm
    bool bHasHalf = false;
    FVector Half = FVector::ZeroVector;  // UE cm, mojulo (x, y, z) extents
    float Radius = 200.f;                // cm (score default 2 m)
    bool bPlanar = true;
};

struct FMojuloPickup
{
    FString Item = TEXT("item");
    FVector Pos = FVector::ZeroVector;
    float Radius = 140.f;                // cm (score default 1.4 m)
    bool bTaken = false;
    AMojuloMarker* Marker = nullptr;
};

struct FMojuloHazard
{
    FVector Pos = FVector::ZeroVector;
    float Radius = 150.f;                // cm (score default 1.5 m)
    float Damage = 20.f;
    float Cool = 0.f;
};

struct FMojuloEntity
{
    FString Id;
    FString Figure;
    bool bHasTranslation = false;
    FVector Pos = FVector::ZeroVector;
    // The locomotion row (score entities[].locomotion): GLB animation
    // names for the clips a kernel plays to make the figure move. Empty =
    // the entity has no travel clips (a statue is honest for it).
    FString IdleClip;
    FString WalkClip;
    FString BoostClip;
};

struct FMojuloScoreData
{
    FString Title;
    FVector Spawn = FVector::ZeroVector; // UE cm
    float Eye = 1.7f;                    // meters (mojulo units)
    float Ground = 0.f;                  // mojulo z
    bool bHasColliders = false;
    float MinColliderZ = 0.f;            // mojulo z of the lowest collider
    TArray<FMojuloEntity> Entities;
    TArray<FMojuloZone> Exits;
    TArray<FMojuloPickup> Pickups;
    TArray<FMojuloHazard> Hazards;
    float SurviveSeconds = -1.f;
    bool bFailOnDeath = false;
    float StartHp = 100.f;
    bool bHasHp = false;
    FString Player;
    FString Soundtrack;
};

struct FMojuloGameLevel
{
    FString Title;
    FString Ref;
    FString GateCompleted;
};

struct FMojuloGameData
{
    FString Title = TEXT("mojulo game");
    TArray<FMojuloGameLevel> Levels;
};

namespace MojuloScore
{
    // THE frame conversion, C++ half: mojulo z-up right-handed meters ->
    // UE z-up left-handed centimeters. MUST stay identical to P() in
    // import_mojulo.py — the machine gate's frame_landmark pins python's;
    // the kernel's spawn/zone/pickup positions ride the same mapping.
    MOJULOKERNEL_API FVector P(double X, double Y, double Z);

    MOJULOKERNEL_API FString PackDir();                       // <Project>/MojuloPack
    MOJULOKERNEL_API FString ScorePathForMap(const FString& MapName);
    MOJULOKERNEL_API bool LoadScore(const FString& JsonPath, FMojuloScoreData& Out);
    MOJULOKERNEL_API bool LoadGame(FMojuloGameData& Out);     // <pack>/game.json
    MOJULOKERNEL_API bool HasMenuMap();

    // Progression: completed level refs, |-joined in Saved/mojulo.completed
    // (the Unity kernel's PlayerPrefs "mojulo.completed" semantics, as a
    // plain debuggable file).
    MOJULOKERNEL_API TSet<FString> ReadCompleted();
    MOJULOKERNEL_API void MarkCompleted(const FString& LevelRef);
}
`;

const scoreCpp = () => `${HEADER_CPP}#include "MojuloScore.h"

#include "Dom/JsonObject.h"
#include "Misc/FileHelper.h"
#include "Misc/PackageName.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"

namespace
{
    bool ReadVec(const TSharedPtr<FJsonObject>& Obj, const FString& Field, FVector& OutUE)
    {
        const TArray<TSharedPtr<FJsonValue>>* Arr = nullptr;
        if (!Obj.IsValid() || !Obj->TryGetArrayField(Field, Arr) || Arr->Num() < 3) return false;
        OutUE = MojuloScore::P((*Arr)[0]->AsNumber(), (*Arr)[1]->AsNumber(), (*Arr)[2]->AsNumber());
        return true;
    }

    TSharedPtr<FJsonObject> ParseFile(const FString& Path)
    {
        FString Text;
        if (!FFileHelper::LoadFileToString(Text, *Path)) return nullptr;
        TSharedPtr<FJsonObject> Root;
        const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Text);
        if (!FJsonSerializer::Deserialize(Reader, Root)) return nullptr;
        return Root;
    }

    FString ProgressPath() { return FPaths::ProjectSavedDir() / TEXT("mojulo.completed"); }
}

namespace MojuloScore
{
    FVector P(double X, double Y, double Z)
    {
        return FVector(X * 100.0, -Y * 100.0, Z * 100.0);
    }

    FString PackDir() { return FPaths::ProjectDir() / TEXT("MojuloPack"); }

    FString ScorePathForMap(const FString& MapName)
    {
        const FString PerLevel = PackDir() / TEXT("levels") / MapName / TEXT("score.json");
        if (FPaths::FileExists(PerLevel)) return PerLevel;
        return PackDir() / TEXT("score.json"); // world scope (U0 pack shape)
    }

    bool LoadScore(const FString& JsonPath, FMojuloScoreData& Out)
    {
        const TSharedPtr<FJsonObject> Root = ParseFile(JsonPath);
        if (!Root.IsValid()) return false;
        Root->TryGetStringField(TEXT("title"), Out.Title);
        ReadVec(Root, TEXT("spawn"), Out.Spawn);
        double Num = 0.0;
        if (Root->TryGetNumberField(TEXT("eye"), Num)) Out.Eye = Num;
        if (Root->TryGetNumberField(TEXT("ground"), Num)) Out.Ground = Num;
        Root->TryGetStringField(TEXT("player"), Out.Player);
        Root->TryGetStringField(TEXT("soundtrack"), Out.Soundtrack);

        const TArray<TSharedPtr<FJsonValue>>* Colliders = nullptr;
        if (Root->TryGetArrayField(TEXT("colliders"), Colliders) && Colliders->Num() > 0)
        {
            Out.bHasColliders = true;
            Out.MinColliderZ = TNumericLimits<float>::Max();
            for (const TSharedPtr<FJsonValue>& V : *Colliders)
            {
                const TSharedPtr<FJsonObject> C = V->AsObject();
                const TArray<TSharedPtr<FJsonValue>>* Min = nullptr;
                if (C.IsValid() && C->TryGetArrayField(TEXT("min"), Min) && Min->Num() >= 3)
                    Out.MinColliderZ = FMath::Min(Out.MinColliderZ, (float)(*Min)[2]->AsNumber());
            }
        }

        const TArray<TSharedPtr<FJsonValue>>* Entities = nullptr;
        if (Root->TryGetArrayField(TEXT("entities"), Entities))
            for (const TSharedPtr<FJsonValue>& V : *Entities)
            {
                const TSharedPtr<FJsonObject> E = V->AsObject();
                if (!E.IsValid()) continue;
                FMojuloEntity Entity;
                E->TryGetStringField(TEXT("id"), Entity.Id);
                E->TryGetStringField(TEXT("figure"), Entity.Figure);
                Entity.bHasTranslation = ReadVec(E, TEXT("translation"), Entity.Pos);
                const TSharedPtr<FJsonObject>* Loco = nullptr;
                if (E->TryGetObjectField(TEXT("locomotion"), Loco) && Loco->IsValid())
                {
                    (*Loco)->TryGetStringField(TEXT("idle"), Entity.IdleClip);
                    (*Loco)->TryGetStringField(TEXT("walk"), Entity.WalkClip);
                    (*Loco)->TryGetStringField(TEXT("boost"), Entity.BoostClip);
                }
                Out.Entities.Add(Entity);
            }

        // The mechanics vocabulary — defaults mirror Unity's MojuloLevel.cs
        // [Serializable] classes exactly (radius 2 m, planar true, pickup
        // 1.4 m, hazard 1.5 m / 20 dmg, survive 30 s, startHp 100).
        const TArray<TSharedPtr<FJsonValue>>* Mechanics = nullptr;
        if (Root->TryGetArrayField(TEXT("mechanics"), Mechanics))
            for (const TSharedPtr<FJsonValue>& V : *Mechanics)
            {
                const TSharedPtr<FJsonObject> M = V->AsObject();
                if (!M.IsValid()) continue;
                FString Kind;
                M->TryGetStringField(TEXT("kind"), Kind);
                if (Kind == TEXT("reach-exit"))
                {
                    FMojuloZone Zone;
                    ReadVec(M, TEXT("at"), Zone.Pos);
                    const TArray<TSharedPtr<FJsonValue>>* Half = nullptr;
                    if (M->TryGetArrayField(TEXT("half"), Half) && Half->Num() >= 3)
                    {
                        Zone.bHasHalf = true;
                        Zone.Half = FVector((*Half)[0]->AsNumber() * 100.0, (*Half)[1]->AsNumber() * 100.0, (*Half)[2]->AsNumber() * 100.0);
                    }
                    if (M->TryGetNumberField(TEXT("radius"), Num)) Zone.Radius = Num * 100.0;
                    M->TryGetBoolField(TEXT("planar"), Zone.bPlanar);
                    Out.Exits.Add(Zone);
                }
                else if (Kind == TEXT("collect"))
                {
                    const TArray<TSharedPtr<FJsonValue>>* Pickups = nullptr;
                    if (M->TryGetArrayField(TEXT("pickups"), Pickups))
                        for (const TSharedPtr<FJsonValue>& PV : *Pickups)
                        {
                            const TSharedPtr<FJsonObject> PO = PV->AsObject();
                            if (!PO.IsValid()) continue;
                            FMojuloPickup Pickup;
                            PO->TryGetStringField(TEXT("item"), Pickup.Item);
                            ReadVec(PO, TEXT("at"), Pickup.Pos);
                            if (PO->TryGetNumberField(TEXT("radius"), Num)) Pickup.Radius = Num * 100.0;
                            Out.Pickups.Add(Pickup);
                        }
                }
                else if (Kind == TEXT("hazard-damage"))
                {
                    Out.bHasHp = true;
                    if (M->TryGetNumberField(TEXT("startHp"), Num)) Out.StartHp = Num;
                    const TArray<TSharedPtr<FJsonValue>>* Hazards = nullptr;
                    if (M->TryGetArrayField(TEXT("hazards"), Hazards))
                        for (const TSharedPtr<FJsonValue>& HV : *Hazards)
                        {
                            const TSharedPtr<FJsonObject> HO = HV->AsObject();
                            if (!HO.IsValid()) continue;
                            FMojuloHazard Hazard;
                            ReadVec(HO, TEXT("at"), Hazard.Pos);
                            if (HO->TryGetNumberField(TEXT("radius"), Num)) Hazard.Radius = Num * 100.0;
                            if (HO->TryGetNumberField(TEXT("damage"), Num)) Hazard.Damage = Num;
                            Out.Hazards.Add(Hazard);
                        }
                }
                else if (Kind == TEXT("fail-on-death"))
                {
                    Out.bFailOnDeath = true;
                    if (!Out.bHasHp)
                    {
                        Out.bHasHp = true;
                        if (M->TryGetNumberField(TEXT("startHp"), Num)) Out.StartHp = Num;
                    }
                }
                else if (Kind == TEXT("survive"))
                {
                    Out.SurviveSeconds = 30.f;
                    if (M->TryGetNumberField(TEXT("seconds"), Num)) Out.SurviveSeconds = Num;
                }
                // Unknown kinds are skipped — ledgered pack-side, never fatal.
            }
        return true;
    }

    bool LoadGame(FMojuloGameData& Out)
    {
        const TSharedPtr<FJsonObject> Root = ParseFile(PackDir() / TEXT("game.json"));
        if (!Root.IsValid()) return false;
        Root->TryGetStringField(TEXT("title"), Out.Title);
        const TArray<TSharedPtr<FJsonValue>>* Levels = nullptr;
        if (Root->TryGetArrayField(TEXT("levels"), Levels))
            for (const TSharedPtr<FJsonValue>& V : *Levels)
            {
                const TSharedPtr<FJsonObject> L = V->AsObject();
                if (!L.IsValid()) continue;
                FMojuloGameLevel Level;
                L->TryGetStringField(TEXT("title"), Level.Title);
                L->TryGetStringField(TEXT("ref"), Level.Ref);
                const TSharedPtr<FJsonObject>* Gate = nullptr;
                if (L->TryGetObjectField(TEXT("gate"), Gate) && Gate->IsValid())
                    (*Gate)->TryGetStringField(TEXT("completed"), Level.GateCompleted);
                if (!Level.Ref.IsEmpty()) Out.Levels.Add(Level);
            }
        return true;
    }

    bool HasMenuMap()
    {
        return FPackageName::DoesPackageExist(TEXT("/Game/MojuloPack/Maps/mojulo-menu"));
    }

    TSet<FString> ReadCompleted()
    {
        TSet<FString> Done;
        FString Text;
        if (FFileHelper::LoadFileToString(Text, *ProgressPath()))
        {
            TArray<FString> Parts;
            Text.ParseIntoArray(Parts, TEXT("|"), true);
            for (const FString& Ref : Parts) Done.Add(Ref.TrimStartAndEnd());
        }
        return Done;
    }

    void MarkCompleted(const FString& LevelRef)
    {
        TSet<FString> Done = ReadCompleted();
        Done.Add(LevelRef);
        FFileHelper::SaveStringToFile(FString::Join(Done, TEXT("|")), *ProgressPath());
    }
}
`;

/* -------------------------------------------------------------- walker --- */

const walkerH = () => `${HEADER_CPP}// AMojuloWalker — the first-person walker, mirror of Runtime/MojuloWalker.cs:
// WASD/arrows + mouse look, Space jump, kill-Z respawn, eye-height camera,
// everything scaled by eyeScale so suit-scale worlds read right. Input is
// POLLED (no Enhanced Input assets, no config edits) — the kernel needs zero
// project wiring, the IMGUI spirit of the Unity kernel.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "MojuloWalker.generated.h"

UCLASS()
class MOJULOKERNEL_API AMojuloWalker : public ACharacter
{
    GENERATED_BODY()

public:
    AMojuloWalker();

    // Called once by the game mode after the score is read.
    void InitFromScore(float Eye, float EyeScale, const FVector& SpawnPos, float KillZ);
    void Respawn();
    float GetEyeMeters() const { return EyeMeters; }
    // Third-person camera for the walking-suit rung: the operator sees the
    // suit they drive. Arm length + socket height in cm (sized from the
    // SUIT's bounds, not the pilot eye — a 6 m arm inside an 18 m suit shows
    // only hull, pinned at the U3 slice). 0 arm restores first person.
    void SetCameraRig(float ArmLength, float SocketHeight);

    virtual void Tick(float DeltaSeconds) override;

private:
    UPROPERTY()
    class USpringArmComponent* CameraArm = nullptr;
    UPROPERTY()
    class UCameraComponent* Camera = nullptr;

    FVector SpawnLocation = FVector::ZeroVector;
    float KillZValue = -100000.f;
    float EyeMeters = 1.7f;
    bool bConfigured = false;
    bool bAutoWalk = false; // -MojuloAutoWalk: headless locomotion probe
};
`;

const walkerCpp = () => `${HEADER_CPP}#include "MojuloWalker.h"

#include "Camera/CameraComponent.h"
#include "Components/CapsuleComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/SpringArmComponent.h"

AMojuloWalker::AMojuloWalker()
{
    PrimaryActorTick.bCanEverTick = true;
    bUseControllerRotationYaw = true;
    CameraArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("MojuloCameraArm"));
    CameraArm->SetupAttachment(GetCapsuleComponent());
    CameraArm->bUsePawnControlRotation = true;
    CameraArm->TargetArmLength = 0.f; // first person by default
    CameraArm->bDoCollisionTest = false;
    Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("MojuloEye"));
    Camera->SetupAttachment(CameraArm);
    Camera->bUsePawnControlRotation = false;
}

void AMojuloWalker::SetCameraRig(float ArmLength, float SocketHeight)
{
    CameraArm->TargetArmLength = FMath::Max(0.f, ArmLength);
    if (SocketHeight > 0.f) CameraArm->SetRelativeLocation(FVector(0.f, 0.f, SocketHeight));
}

void AMojuloWalker::InitFromScore(float Eye, float EyeScale, const FVector& SpawnPos, float KillZ)
{
    EyeMeters = Eye > 0.f ? Eye : 1.7f;
    SpawnLocation = SpawnPos;
    KillZValue = KillZ;

    // Capsule: height = eye, like the Unity CharacterController; UE works in
    // half-heights and centimeters.
    const float HalfHeight = FMath::Max(30.f, EyeMeters * 50.f);
    const float Radius = FMath::Min(HalfHeight - 1.f, FMath::Max(20.f, 40.f * EyeScale));
    GetCapsuleComponent()->SetCapsuleSize(Radius, HalfHeight);
    CameraArm->SetRelativeLocation(FVector(0.f, 0.f, HalfHeight - 10.f * EyeScale));

    // Unity: speed 6 m/s, jump 4.5 m/s, gravity 9.8 m/s² — all ×eyeScale.
    UCharacterMovementComponent* Move = GetCharacterMovement();
    Move->MaxWalkSpeed = 600.f * EyeScale;
    Move->JumpZVelocity = 450.f * EyeScale;
    Move->GravityScale = EyeScale;
    Move->AirControl = 0.35f;

    SetActorLocation(SpawnLocation + FVector(0.f, 0.f, HalfHeight + 10.f), false, nullptr, ETeleportType::TeleportPhysics);
    bAutoWalk = FParse::Param(FCommandLine::Get(), TEXT("MojuloAutoWalk"));
    bConfigured = true;
}

void AMojuloWalker::Respawn()
{
    const float HalfHeight = GetCapsuleComponent()->GetScaledCapsuleHalfHeight();
    SetActorLocation(SpawnLocation + FVector(0.f, 0.f, HalfHeight + 10.f), false, nullptr, ETeleportType::TeleportPhysics);
    GetCharacterMovement()->Velocity = FVector::ZeroVector;
}

void AMojuloWalker::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    if (!bConfigured) return;
    APlayerController* PC = Cast<APlayerController>(GetController());
    if (PC == nullptr) return;

    PC->bShowMouseCursor = false;

    float MouseX = 0.f, MouseY = 0.f;
    PC->GetInputMouseDelta(MouseX, MouseY);
    AddControllerYawInput(MouseX * 0.8f);
    AddControllerPitchInput(-MouseY * 0.8f);

    const FRotator Yaw(0.f, GetControlRotation().Yaw, 0.f);
    FVector Dir = FVector::ZeroVector;
    if (PC->IsInputKeyDown(EKeys::W) || PC->IsInputKeyDown(EKeys::Up)) Dir += FRotationMatrix(Yaw).GetUnitAxis(EAxis::X);
    if (PC->IsInputKeyDown(EKeys::S) || PC->IsInputKeyDown(EKeys::Down)) Dir -= FRotationMatrix(Yaw).GetUnitAxis(EAxis::X);
    if (PC->IsInputKeyDown(EKeys::D) || PC->IsInputKeyDown(EKeys::Right)) Dir += FRotationMatrix(Yaw).GetUnitAxis(EAxis::Y);
    if (PC->IsInputKeyDown(EKeys::A) || PC->IsInputKeyDown(EKeys::Left)) Dir -= FRotationMatrix(Yaw).GetUnitAxis(EAxis::Y);
    if (bAutoWalk) Dir += FRotationMatrix(Yaw).GetUnitAxis(EAxis::X);
    if (!Dir.IsNearlyZero()) AddMovementInput(Dir.GetSafeNormal(), 1.f);

    if (PC->WasInputKeyJustPressed(EKeys::SpaceBar)) Jump();

    if (GetActorLocation().Z < KillZValue) Respawn();
}
`;

/* ----------------------------------------------------------- game mode --- */

const gameModeH = () => `${HEADER_CPP}// AMojuloGameMode — the level interpreter, mirror of Runtime/MojuloLevel.cs
// (+ the completion flow of MojuloGame.cs): reads the level's score.json,
// configures the walker, spawns pickup/hazard markers, performs the
// mechanics vocabulary each Tick, persists completion, returns to the menu.
// AMojuloMarker is the runtime placeholder body (gold pickups, red hazards)
// — engine basic shapes, no pack content.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "GameFramework/GameModeBase.h"
#include "MojuloScore.h"
#include "MojuloGameMode.generated.h"

UCLASS()
class MOJULOKERNEL_API AMojuloMarker : public AActor
{
    GENERATED_BODY()

public:
    AMojuloMarker();
    // Engine sphere/cube, scaled and tinted. Hazards draw opaque (stock
    // BasicShapeMaterial has no translucent variant) — an honest, visible
    // approximation of Unity's translucent danger sphere.
    void SetShape(bool bSphere, const FVector& WorldScale, const FLinearColor& Color);

    UPROPERTY()
    class UStaticMeshComponent* Mesh = nullptr;
};

UCLASS()
class MOJULOKERNEL_API AMojuloGameMode : public AGameModeBase
{
    GENERATED_BODY()

public:
    AMojuloGameMode();

    virtual void BeginPlay() override;
    virtual void Tick(float DeltaSeconds) override;

    // Read by AMojuloHUD.
    FString State = TEXT("playing"); // playing | complete | failed
    FString Banner;
    float Hp = -1.f;
    float SurviveLeft = -1.f;
    TMap<FString, int32> Bag;

protected:
    void ConfigureWalker();
    void SpawnMechanicMarkers();
    void StartMusic();
    float BodyDistance(const FVector& Target) const;
    bool ZoneHit(const FMojuloZone& Zone, const FVector& Pos) const;
    void Complete();
    void Fail();
    void ResetLevel();
    void ToMenu();

    // Locomotion (the walking-suits rung): Interchange imports the GLB's
    // rigid-hierarchy animations as LevelSequence assets (pinned at U2) —
    // the kernel indexes them by sanitized clip name and plays them with
    // ULevelSequencePlayer. Ambient entities loop their idle; the player's
    // suit follows the walker and swaps walk/idle by speed (third person).
    void BuildSequenceIndex();
    class ULevelSequence* SequenceForClip(const FString& ClipName) const;
    // Interchange's sequence transform tracks are PARENT-RELATIVE (pinned at
    // U3: transform origins are ignored — the z-suit idled at 860 m, not
    // 1720 m — and clips pose parts around their wrapper). So figures are
    // placed by their WRAPPER actor, and the player suit follows the walker
    // by wrapper SetActorLocation + a yaw delta composed on the imported
    // base quat (never a raw rotator — that strips the frame correction).
    class ULevelSequencePlayer* PlayClip(const FString& ClipName, bool bLoop);
    void SetupLocomotion();
    void TickPlayerSuit();
    AActor* FindActorByCleanName(const FString& Wanted) const;
    static void SetActorTreeHidden(AActor* Root, bool bHidden);
    static void SetActorTreeMovable(AActor* Root);
    static void SetActorTreeCollision(AActor* Root, bool bEnabled);

    FMojuloScoreData Score;
    FString LevelRef;
    bool bScoreLoaded = false;
    float EyeScale = 1.f;
    float PendingMenuAt = -1.f;
    float PendingResetAt = -1.f;

    // -MojuloShot=<seconds>: take a HighResShot after N seconds of play —
    // the machine-side eyes proxy (a frame-1 ExecCmds shot fires before the
    // kernel's first tick and shows the un-posed world).
    float ShotAt = -1.f;
    bool bShotTaken = false;

    TMap<FString, FSoftObjectPath> SequenceIndex;
    UPROPERTY()
    TArray<class ALevelSequenceActor*> SequenceActors; // keeps players alive
    UPROPERTY()
    AActor* PlayerSuit = nullptr;
    UPROPERTY()
    class ULevelSequencePlayer* SuitIdlePlayer = nullptr;
    UPROPERTY()
    class ULevelSequencePlayer* SuitWalkPlayer = nullptr;
    UPROPERTY()
    TArray<AActor*> DebugFigures; // -MojuloShot dumps their part positions
    FQuat SuitBaseQuat = FQuat::Identity;
    float BaseControlYaw = 0.f;
    bool bSuitWalking = false;

    UPROPERTY()
    class AMojuloWalker* Walker = nullptr;
};
`;

const gameModeCpp = () => `${HEADER_CPP}#include "MojuloGameMode.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "Kismet/GameplayStatics.h"
#include "LevelSequence.h"
#include "LevelSequenceActor.h"
#include "LevelSequencePlayer.h"
#include "Materials/Material.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "MojuloHUD.h"
#include "MojuloWalker.h"
#include "Sound/SoundWave.h"

namespace
{
    // The same sanitization import_mojulo.py uses to survive Interchange's
    // punctuation stripping ('entity:hero' -> 'entity_hero',
    // 'gframe_mk2_multi:idle' -> 'gframe_mk2_multi_idle').
    FString CleanName(const FString& S)
    {
        FString Out;
        Out.Reserve(S.Len());
        for (const TCHAR C : S) Out.AppendChar(FChar::IsAlnum(C) ? C : TEXT('_'));
        return Out;
    }
}

AMojuloMarker::AMojuloMarker()
{
    PrimaryActorTick.bCanEverTick = false;
    Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MarkerMesh"));
    RootComponent = Mesh;
    Mesh->SetMobility(EComponentMobility::Movable);
    Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
}

void AMojuloMarker::SetShape(bool bSphere, const FVector& WorldScale, const FLinearColor& Color)
{
    UStaticMesh* Shape = LoadObject<UStaticMesh>(nullptr, bSphere
        ? TEXT("/Engine/BasicShapes/Sphere.Sphere")
        : TEXT("/Engine/BasicShapes/Cube.Cube"));
    if (Shape != nullptr) Mesh->SetStaticMesh(Shape);
    Mesh->SetWorldScale3D(WorldScale);
    UMaterial* Base = LoadObject<UMaterial>(nullptr, TEXT("/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"));
    if (Base != nullptr)
    {
        UMaterialInstanceDynamic* Mid = UMaterialInstanceDynamic::Create(Base, this);
        Mid->SetVectorParameterValue(FName(TEXT("Color")), Color);
        Mesh->SetMaterial(0, Mid);
    }
}

AMojuloGameMode::AMojuloGameMode()
{
    PrimaryActorTick.bCanEverTick = true;
    DefaultPawnClass = AMojuloWalker::StaticClass();
    HUDClass = AMojuloHUD::StaticClass();
}

void AMojuloGameMode::BeginPlay()
{
    Super::BeginPlay();
    FString Map = GetWorld()->GetMapName();
    Map.RemoveFromStart(GetWorld()->StreamingLevelsPrefix); // strips UEDPIE_N_
    LevelRef = Map;
    bScoreLoaded = MojuloScore::LoadScore(MojuloScore::ScorePathForMap(Map), Score);
    if (!bScoreLoaded)
    {
        UE_LOG(LogTemp, Error, TEXT("[mojulo] no score.json for map '%s' under %s"), *Map, *MojuloScore::PackDir());
        return;
    }
    EyeScale = FMath::Max(0.5f, Score.Eye / 1.7f);
    SpawnMechanicMarkers();
    StartMusic();
    float ShotSeconds = 0.f;
    if (FParse::Value(FCommandLine::Get(), TEXT("MojuloShot="), ShotSeconds)) ShotAt = ShotSeconds;
}

void AMojuloGameMode::ConfigureWalker()
{
    AMojuloWalker* Pawn = Cast<AMojuloWalker>(UGameplayStatics::GetPlayerPawn(this, 0));
    if (Pawn == nullptr) return;
    // Kill-Z: 100 m under the lowest collider, or 300 m under spawn — the
    // Unity walker's killY, in centimeters.
    float KillZ = Score.Spawn.Z - 30000.f;
    if (Score.bHasColliders) KillZ = Score.MinColliderZ * 100.f - 10000.f;
    Pawn->InitFromScore(Score.Eye, EyeScale, Score.Spawn, KillZ);
    Walker = Pawn;
    Hp = Score.bHasHp ? Score.StartHp : -1.f;
    SurviveLeft = Score.SurviveSeconds;
    SetupLocomotion();
}

AActor* AMojuloGameMode::FindActorByCleanName(const FString& Wanted) const
{
    const FString Want = CleanName(Wanted);
    for (TActorIterator<AActor> It(GetWorld()); It; ++It)
    {
#if WITH_EDITOR
        const FString Label = It->GetActorLabel();
#else
        const FString Label = It->GetName();
#endif
        if (CleanName(Label) == Want) return *It;
    }
    return nullptr;
}

void AMojuloGameMode::SetActorTreeHidden(AActor* Root, bool bHidden)
{
    // Interchange imports one actor per GLB node — hiding the wrapper alone
    // leaves the body visible (pinned at U2: the "hidden" player seat stood
    // in every U0 screenshot). Walk the attachment tree.
    if (Root == nullptr) return;
    Root->SetActorHiddenInGame(bHidden);
    TArray<AActor*> Children;
    Root->GetAttachedActors(Children);
    for (AActor* Child : Children) SetActorTreeHidden(Child, bHidden);
}

void AMojuloGameMode::SetActorTreeCollision(AActor* Root, bool bEnabled)
{
    // The player's suit is a cosmetic FOLLOWER — its imported part colliders
    // wedge the pilot capsule at spawn (pinned at U3: WASD ran in place
    // while a persistent auto-walk force squeezed free). Blocking is the
    // score colliders' job, never the suit body's.
    if (Root == nullptr) return;
    Root->SetActorEnableCollision(bEnabled);
    TArray<AActor*> Children;
    Root->GetAttachedActors(Children);
    for (AActor* Child : Children) SetActorTreeCollision(Child, bEnabled);
}

void AMojuloGameMode::SetActorTreeMovable(AActor* Root)
{
    // Interchange imports scene actors STATIC — SetActorLocation fails
    // silently and sequences cannot pose parts (pinned at the U3 eyes gate:
    // the suit stood frozen in rest pose). Movable, whole tree.
    if (Root == nullptr) return;
    if (USceneComponent* RootComp = Root->GetRootComponent())
        RootComp->SetMobility(EComponentMobility::Movable);
    TArray<AActor*> Children;
    Root->GetAttachedActors(Children);
    for (AActor* Child : Children) SetActorTreeMovable(Child);
}

void AMojuloGameMode::BuildSequenceIndex()
{
    // A game pack imports one asset subtree PER LEVEL
    // (/Game/MojuloPack/Levels/<ref>/model/...), so a multi-level pack holds
    // N copies of every shared figure's sequences under identical names.
    // Indexing the whole pack let the LAST level imported win — sequences
    // whose bindings point at another map's actors (pinned before U4; the
    // one-level slice could not see it). Scope to THIS level's subtree; a
    // world-scope pack (U0 shape, assets straight under the root) has no
    // Levels/ subtree and takes the root.
    const FAssetRegistryModule& Registry = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
    TArray<FAssetData> Assets;
    Registry.Get().GetAssetsByClass(ULevelSequence::StaticClass()->GetClassPathName(), Assets, true);
    const FString LevelRoot = FString(TEXT("/Game/MojuloPack/Levels/")) + LevelRef;
    TMap<FString, FSoftObjectPath> Scoped, PackWide;
    for (const FAssetData& Asset : Assets)
    {
        const FString Path = Asset.PackagePath.ToString();
        if (!Path.StartsWith(TEXT("/Game/MojuloPack"))) continue;
        const FString Key = CleanName(Asset.AssetName.ToString());
        PackWide.Add(Key, Asset.ToSoftObjectPath());
        if (Path == LevelRoot || Path.StartsWith(LevelRoot + TEXT("/"))) Scoped.Add(Key, Asset.ToSoftObjectPath());
    }
    SequenceIndex = Scoped.Num() > 0 ? Scoped : PackWide;
}

ULevelSequence* AMojuloGameMode::SequenceForClip(const FString& ClipName) const
{
    const FSoftObjectPath* Path = SequenceIndex.Find(CleanName(ClipName));
    return Path != nullptr ? Cast<ULevelSequence>(Path->TryLoad()) : nullptr;
}

ULevelSequencePlayer* AMojuloGameMode::PlayClip(const FString& ClipName, bool bLoop)
{
    ULevelSequence* Sequence = SequenceForClip(ClipName);
    if (Sequence == nullptr)
    {
        UE_LOG(LogTemp, Warning, TEXT("[mojulo] no LevelSequence for clip '%s'"), *ClipName);
        return nullptr;
    }
    FMovieSceneSequencePlaybackSettings Settings;
    if (bLoop) Settings.LoopCount.Value = -1;
    ALevelSequenceActor* OutActor = nullptr;
    ULevelSequencePlayer* Player = ULevelSequencePlayer::CreateLevelSequencePlayer(GetWorld(), Sequence, Settings, OutActor);
    if (OutActor != nullptr) SequenceActors.Add(OutActor);
    if (Player != nullptr) Player->Play();
    return Player;
}

void AMojuloGameMode::SetupLocomotion()
{
    BuildSequenceIndex();

    // Ambient entities: everything with an idle clip breathes instead of
    // standing as a statue. First-claimant figures only — a figure bakes
    // ONCE, later entities sharing it have no body of their own, and two
    // players on one sequence fight.
    TSet<FString> Claimed;
    // The player's FIGURE is claimed by the player — a second entity sharing
    // it must not play a competing idle on the one baked body (pinned by the
    // U3 dump: the ring's en_unit idled the player's own suit).
    for (const FMojuloEntity& Entity : Score.Entities)
        if (Entity.Id == Score.Player && !Entity.Figure.IsEmpty()) Claimed.Add(Entity.Figure);
    for (const FMojuloEntity& Entity : Score.Entities)
    {
        if (Entity.Id == Score.Player || Entity.IdleClip.IsEmpty()) continue;
        if (!Entity.Figure.IsEmpty())
        {
            if (Claimed.Contains(Entity.Figure)) continue;
            Claimed.Add(Entity.Figure);
        }
        AActor* Figure = FindActorByCleanName(!Entity.Figure.IsEmpty() ? Entity.Figure : TEXT("entity:") + Entity.Id);
        SetActorTreeMovable(Figure);
        if (Figure != nullptr) DebugFigures.Add(Figure);
        PlayClip(Entity.IdleClip, true);
    }

    // The player's suit: visible, third person, following the walker —
    // "walk the arena AS the suit". Frame/facing composition is UNPINNED
    // until the U3 arena slice eyes it.
    const FMojuloEntity* PlayerEntity = Score.Entities.FindByPredicate(
        [this](const FMojuloEntity& E) { return E.Id == Score.Player; });
    if (PlayerEntity == nullptr) return;
    AActor* Seat = FindActorByCleanName(!PlayerEntity->Figure.IsEmpty() ? PlayerEntity->Figure : TEXT("entity:") + PlayerEntity->Id);
    if (PlayerEntity->IdleClip.IsEmpty() && PlayerEntity->WalkClip.IsEmpty())
    {
        // First person: no travel clips — make sure the WHOLE seat body is
        // hidden (the import-time hide misses attached child actors) and
        // never collides with the pilot.
        SetActorTreeHidden(Seat, true);
        SetActorTreeCollision(Seat, false);
        return;
    }
    PlayerSuit = Seat;
    if (PlayerSuit == nullptr || Walker == nullptr) return;
    SetActorTreeMovable(PlayerSuit);
    SetActorTreeCollision(PlayerSuit, false);
    SetActorTreeHidden(PlayerSuit, false);
    SuitBaseQuat = PlayerSuit->GetActorQuat();
    BaseControlYaw = Walker->GetControlRotation().Yaw;
    // Frame the SUIT, not the pilot: bounds over the whole attachment tree
    // (one actor per GLB node), arm back ~2 suit-heights, camera raised to
    // the suit's chest line.
    FBox Bounds(ForceInit);
    TArray<AActor*> Tree;
    Tree.Add(PlayerSuit);
    for (int32 i = 0; i < Tree.Num(); i++)
    {
        FVector Origin = FVector::ZeroVector, Extent = FVector::ZeroVector;
        Tree[i]->GetActorBounds(false, Origin, Extent);
        if (!Extent.IsNearlyZero()) Bounds += FBox(Origin - Extent, Origin + Extent);
        TArray<AActor*> Children;
        Tree[i]->GetAttachedActors(Children);
        Tree.Append(Children);
    }
    const float SuitHeight = Bounds.IsValid ? (Bounds.Max.Z - Bounds.Min.Z) : Score.Eye * 100.f;
    Walker->SetCameraRig(FMath::Max(Score.Eye * 350.f, SuitHeight * 2.f), SuitHeight * 0.55f);
    if (!PlayerEntity->IdleClip.IsEmpty()) SuitIdlePlayer = PlayClip(PlayerEntity->IdleClip, true);
    if (!PlayerEntity->WalkClip.IsEmpty())
    {
        SuitWalkPlayer = PlayClip(PlayerEntity->WalkClip, true);
        if (SuitWalkPlayer != nullptr) SuitWalkPlayer->Pause();
    }
}

void AMojuloGameMode::TickPlayerSuit()
{
    if (PlayerSuit == nullptr || Walker == nullptr) return;
    // Wrapper follow: sequences pose parts RELATIVE to the wrapper, so
    // moving/turning the wrapper carries the animated suit. Yaw is a delta
    // composed on the imported base quat (a raw rotator lays it face-down).
    const FVector Feet = Walker->GetActorLocation() - FVector(0.f, 0.f, Walker->GetSimpleCollisionHalfHeight());
    PlayerSuit->SetActorLocation(Feet);
    const float DeltaYaw = Walker->GetControlRotation().Yaw - BaseControlYaw;
    PlayerSuit->SetActorRotation(FQuat(FRotator(0.f, DeltaYaw, 0.f)) * SuitBaseQuat);

    const bool bMoving = Walker->GetVelocity().Size2D() > 60.f * EyeScale;
    if (bMoving == bSuitWalking) return;
    bSuitWalking = bMoving;
    if (SuitWalkPlayer != nullptr && SuitIdlePlayer != nullptr)
    {
        if (bMoving) { SuitIdlePlayer->Pause(); SuitWalkPlayer->Play(); }
        else { SuitWalkPlayer->Pause(); SuitIdlePlayer->Play(); }
    }
}

void AMojuloGameMode::SpawnMechanicMarkers()
{
    UWorld* World = GetWorld();
    for (FMojuloPickup& Pickup : Score.Pickups)
    {
        AMojuloMarker* Marker = World->SpawnActor<AMojuloMarker>(Pickup.Pos + FVector(0.f, 0.f, 60.f * EyeScale), FRotator::ZeroRotator);
        const float S = 0.5f * EyeScale;
        Marker->SetShape(true, FVector(S), FLinearColor(0.98f, 0.85f, 0.25f));
        Pickup.Marker = Marker;
    }
    for (const FMojuloHazard& Hazard : Score.Hazards)
    {
        AMojuloMarker* Marker = World->SpawnActor<AMojuloMarker>(Hazard.Pos, FRotator::ZeroRotator);
        const float S = Hazard.Radius * 2.f / 100.f;
        Marker->SetShape(true, FVector(S), FLinearColor(0.95f, 0.25f, 0.2f));
    }
}

void AMojuloGameMode::StartMusic()
{
    if (Score.Soundtrack.IsEmpty()) return;
    const FString Path = FString::Printf(TEXT("/Game/MojuloPack/Audio/%s.%s"), *Score.Soundtrack, *Score.Soundtrack);
    USoundWave* Wave = LoadObject<USoundWave>(nullptr, *Path);
    if (Wave != nullptr) UGameplayStatics::SpawnSound2D(this, Wave);
    else UE_LOG(LogTemp, Warning, TEXT("[mojulo] soundtrack asset missing: %s"), *Path);
}

float AMojuloGameMode::BodyDistance(const FVector& Target) const
{
    // Distance to the walker BODY (feet -> head segment), mirror of Unity's
    // BodyDistance — a chest-height hazard must still connect.
    const FVector Feet = Walker->GetActorLocation() - FVector(0.f, 0.f, Walker->GetSimpleCollisionHalfHeight());
    const float Z = FMath::Clamp(Target.Z, Feet.Z, Feet.Z + Walker->GetEyeMeters() * 100.f);
    return FVector::Dist(Target, FVector(Feet.X, Feet.Y, Z));
}

bool AMojuloGameMode::ZoneHit(const FMojuloZone& Zone, const FVector& Pos) const
{
    if (Zone.bHasHalf)
    {
        // Half extents are mojulo (x, y, z); UE y is negated mojulo y but
        // extents are unsigned — planar test is x/y, tall test adds z.
        if (FMath::Abs(Pos.X - Zone.Pos.X) > Zone.Half.X || FMath::Abs(Pos.Y - Zone.Pos.Y) > Zone.Half.Y) return false;
        return Zone.bPlanar || FMath::Abs(Pos.Z - Zone.Pos.Z) <= Zone.Half.Z;
    }
    if (Zone.bPlanar)
        return FVector2D(Pos.X - Zone.Pos.X, Pos.Y - Zone.Pos.Y).Size() <= Zone.Radius;
    return FVector::Dist(Pos, Zone.Pos) <= Zone.Radius;
}

void AMojuloGameMode::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    if (!bScoreLoaded) return;
    if (Walker == nullptr) { ConfigureWalker(); if (Walker == nullptr) return; }

    TickPlayerSuit();

    if (ShotAt >= 0.f && !bShotTaken && GetWorld()->GetTimeSeconds() >= ShotAt)
    {
        bShotTaken = true;
        if (APlayerController* ShotPC = UGameplayStatics::GetPlayerController(this, 0))
            ShotPC->ConsoleCommand(TEXT("HighResShot 1280x720"));
        auto Dump = [](const TCHAR* Tag, AActor* Figure)
        {
            if (Figure == nullptr) return;
            TArray<AActor*> Children;
            Figure->GetAttachedActors(Children);
            const FVector Part = Children.Num() ? Children[0]->GetActorLocation() : FVector::ZeroVector;
            UE_LOG(LogTemp, Display, TEXT("[mojulo-dump] %s %s wrapper=(%.0f,%.0f,%.0f) part0=(%.0f,%.0f,%.0f) kids=%d"),
                Tag, *Figure->GetName(), Figure->GetActorLocation().X, Figure->GetActorLocation().Y, Figure->GetActorLocation().Z,
                Part.X, Part.Y, Part.Z, Children.Num());
        };
        for (AActor* Figure : DebugFigures) Dump(TEXT("ambient"), Figure);
        Dump(TEXT("player"), PlayerSuit);
        if (Walker != nullptr)
            UE_LOG(LogTemp, Display, TEXT("[mojulo-dump] walker=(%.0f,%.0f,%.0f)"),
                Walker->GetActorLocation().X, Walker->GetActorLocation().Y, Walker->GetActorLocation().Z);
    }

    const float Now = GetWorld()->GetTimeSeconds();
    if (PendingMenuAt >= 0.f && Now >= PendingMenuAt) { ToMenu(); return; }
    if (PendingResetAt >= 0.f && Now >= PendingResetAt) { PendingResetAt = -1.f; ResetLevel(); }
    if (State != TEXT("playing")) return;

    APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
    if (PC != nullptr && PC->WasInputKeyJustPressed(EKeys::M) && MojuloScore::HasMenuMap()) { ToMenu(); return; }

    const FVector Pos = Walker->GetActorLocation() - FVector(0.f, 0.f, Walker->GetSimpleCollisionHalfHeight());
    for (const FMojuloZone& Zone : Score.Exits)
        if (ZoneHit(Zone, Pos)) { Complete(); return; }

    if (SurviveLeft >= 0.f)
    {
        SurviveLeft = FMath::Max(0.f, SurviveLeft - DeltaSeconds);
        if (SurviveLeft == 0.f) { Complete(); return; }
    }

    for (FMojuloPickup& Pickup : Score.Pickups)
        if (!Pickup.bTaken && BodyDistance(Pickup.Pos) <= Pickup.Radius + 40.f * EyeScale)
        {
            Pickup.bTaken = true;
            if (Pickup.Marker != nullptr) Pickup.Marker->SetActorHiddenInGame(true);
            Bag.FindOrAdd(Pickup.Item) += 1;
            UE_LOG(LogTemp, Display, TEXT("moj: picked up %s"), *Pickup.Item);
        }

    for (FMojuloHazard& Hazard : Score.Hazards)
    {
        Hazard.Cool = FMath::Max(0.f, Hazard.Cool - DeltaSeconds);
        if (Hazard.Cool == 0.f && BodyDistance(Hazard.Pos) <= Hazard.Radius + 40.f * EyeScale)
        {
            Hazard.Cool = 0.8f; // the Unity kernel's HazardCooldown
            Hp = FMath::Max(0.f, Hp - Hazard.Damage);
            UE_LOG(LogTemp, Display, TEXT("moj: hazard hit, hp %d"), (int32)Hp);
            if (Score.bFailOnDeath && Hp <= 0.f) { Fail(); return; }
        }
    }
}

void AMojuloGameMode::Complete()
{
    State = TEXT("complete");
    Banner = TEXT("LEVEL COMPLETE");
    UE_LOG(LogTemp, Display, TEXT("moj: level complete"));
    MojuloScore::MarkCompleted(LevelRef);
    if (MojuloScore::HasMenuMap()) PendingMenuAt = GetWorld()->GetTimeSeconds() + 1.5f;
}

void AMojuloGameMode::Fail()
{
    State = TEXT("failed");
    Banner = TEXT("FAILED");
    UE_LOG(LogTemp, Display, TEXT("moj: level failed"));
    if (MojuloScore::HasMenuMap()) PendingMenuAt = GetWorld()->GetTimeSeconds() + 1.5f;
    else PendingResetAt = GetWorld()->GetTimeSeconds() + 1.5f;
}

void AMojuloGameMode::ResetLevel()
{
    Banner.Empty();
    Hp = Score.bHasHp ? Score.StartHp : -1.f;
    Bag.Empty();
    for (FMojuloPickup& Pickup : Score.Pickups)
    {
        Pickup.bTaken = false;
        if (Pickup.Marker != nullptr) Pickup.Marker->SetActorHiddenInGame(false);
    }
    SurviveLeft = Score.SurviveSeconds;
    if (Walker != nullptr) Walker->Respawn();
    State = TEXT("playing");
}

void AMojuloGameMode::ToMenu()
{
    UGameplayStatics::OpenLevel(this, FName(TEXT("/Game/MojuloPack/Maps/mojulo-menu")));
}
`;

/* ----------------------------------------------------------------- HUD --- */

const hudH = () => `${HEADER_CPP}// AMojuloHUD — the canvas HUD, mirror of MojuloLevel.OnGUI: HP / SURVIVE /
// bag counts top-left, centered LEVEL COMPLETE / FAILED banner. Canvas
// DrawText is UE's zero-asset analogue of IMGUI.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/HUD.h"
#include "MojuloHUD.generated.h"

UCLASS()
class MOJULOKERNEL_API AMojuloHUD : public AHUD
{
    GENERATED_BODY()

public:
    virtual void DrawHUD() override;
};
`;

const hudCpp = () => `${HEADER_CPP}#include "MojuloHUD.h"

#include "Engine/Canvas.h"
#include "Engine/Engine.h"
#include "Engine/Font.h"
#include "MojuloGameMode.h"

void AMojuloHUD::DrawHUD()
{
    Super::DrawHUD();
    AMojuloGameMode* Mode = GetWorld() ? GetWorld()->GetAuthGameMode<AMojuloGameMode>() : nullptr;
    if (Mode == nullptr || Canvas == nullptr) return;
    UFont* Font = GEngine->GetLargeFont();

    TArray<FString> Parts;
    if (Mode->Hp >= 0.f) Parts.Add(FString::Printf(TEXT("HP %d"), FMath::CeilToInt(Mode->Hp)));
    if (Mode->SurviveLeft >= 0.f) Parts.Add(FString::Printf(TEXT("SURVIVE %d"), FMath::CeilToInt(Mode->SurviveLeft)));
    for (const TPair<FString, int32>& Item : Mode->Bag)
        Parts.Add(FString::Printf(TEXT("%s \\u00d7%d"), *Item.Key.ToUpper(), Item.Value));
    if (Parts.Num() > 0)
        DrawText(FString::Join(Parts, TEXT("   ")), FLinearColor::White, 16.f, 12.f, Font, 1.4f);

    if (!Mode->Banner.IsEmpty())
    {
        const FLinearColor Color = Mode->State == TEXT("failed") ? FLinearColor(1.f, 0.35f, 0.3f) : FLinearColor::White;
        const float Scale = 3.f;
        float W = 0.f, H = 0.f;
        GetTextSize(Mode->Banner, W, H, Font, Scale);
        DrawText(Mode->Banner, Color, (Canvas->SizeX - W) / 2.f, (Canvas->SizeY - H) / 2.f, Font, Scale);
    }
}
`;

/* ---------------------------------------------------------------- menu --- */

const menuH = () => `${HEADER_CPP}// AMojuloMenuGameMode + AMojuloMenuHUD — the menu, mirror of MojuloMenu.cs:
// level list from game.json, [done] / [locked] marks from the progression
// file and gates. Keyboard-driven (Up/Down + Enter), spectator pawn, canvas
// text — zero assets, zero scene wiring.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "GameFramework/HUD.h"
#include "MojuloScore.h"
#include "MojuloMenuGameMode.generated.h"

UCLASS()
class MOJULOKERNEL_API AMojuloMenuGameMode : public AGameModeBase
{
    GENERATED_BODY()

public:
    AMojuloMenuGameMode();

    virtual void BeginPlay() override;
    virtual void Tick(float DeltaSeconds) override;

    FMojuloGameData Game;
    TSet<FString> Done;
    int32 Selected = 0;

    bool IsLocked(const FMojuloGameLevel& Level) const;
};

UCLASS()
class MOJULOKERNEL_API AMojuloMenuHUD : public AHUD
{
    GENERATED_BODY()

public:
    virtual void DrawHUD() override;
};
`;

const menuCpp = () => `${HEADER_CPP}#include "MojuloMenuGameMode.h"

#include "Engine/Canvas.h"
#include "Engine/Engine.h"
#include "Engine/Font.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundWave.h"

AMojuloMenuGameMode::AMojuloMenuGameMode()
{
    PrimaryActorTick.bCanEverTick = true;
    bStartPlayersAsSpectators = true;
    HUDClass = AMojuloMenuHUD::StaticClass();
}

void AMojuloMenuGameMode::BeginPlay()
{
    Super::BeginPlay();
    MojuloScore::LoadGame(Game);
    Done = MojuloScore::ReadCompleted();
    APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
    if (PC != nullptr) { PC->bShowMouseCursor = true; PC->SetIgnoreMoveInput(true); }
    USoundWave* Wave = LoadObject<USoundWave>(nullptr, TEXT("/Game/MojuloPack/Audio/menu.menu"));
    if (Wave != nullptr) UGameplayStatics::SpawnSound2D(this, Wave);
}

bool AMojuloMenuGameMode::IsLocked(const FMojuloGameLevel& Level) const
{
    return !Level.GateCompleted.IsEmpty() && !Done.Contains(Level.GateCompleted);
}

void AMojuloMenuGameMode::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    if (Game.Levels.Num() == 0) return;
    APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
    if (PC == nullptr) return;
    if (PC->WasInputKeyJustPressed(EKeys::Down) || PC->WasInputKeyJustPressed(EKeys::S))
        Selected = (Selected + 1) % Game.Levels.Num();
    if (PC->WasInputKeyJustPressed(EKeys::Up) || PC->WasInputKeyJustPressed(EKeys::W))
        Selected = (Selected + Game.Levels.Num() - 1) % Game.Levels.Num();
    if (PC->WasInputKeyJustPressed(EKeys::Enter) || PC->WasInputKeyJustPressed(EKeys::SpaceBar))
    {
        const FMojuloGameLevel& Level = Game.Levels[Selected];
        if (!IsLocked(Level))
            UGameplayStatics::OpenLevel(this, FName(*(FString(TEXT("/Game/MojuloPack/Maps/")) + Level.Ref)));
    }
}

void AMojuloMenuHUD::DrawHUD()
{
    Super::DrawHUD();
    AMojuloMenuGameMode* Mode = GetWorld() ? GetWorld()->GetAuthGameMode<AMojuloMenuGameMode>() : nullptr;
    if (Mode == nullptr || Canvas == nullptr) return;
    UFont* Font = GEngine->GetLargeFont();

    float W = 0.f, H = 0.f;
    GetTextSize(Mode->Game.Title, W, H, Font, 2.6f);
    float Y = Canvas->SizeY * 0.22f;
    DrawText(Mode->Game.Title, FLinearColor::White, (Canvas->SizeX - W) / 2.f, Y, Font, 2.6f);
    Y += H + 40.f;

    for (int32 i = 0; i < Mode->Game.Levels.Num(); i++)
    {
        const FMojuloGameLevel& Level = Mode->Game.Levels[i];
        FString Label = Level.Title.IsEmpty() ? Level.Ref : Level.Title;
        if (Mode->Done.Contains(Level.Ref)) Label += TEXT("  [done]");
        const bool bLocked = Mode->IsLocked(Level);
        if (bLocked) Label += TEXT("  [locked]");
        if (i == Mode->Selected) Label = TEXT("> ") + Label;
        const FLinearColor Color = bLocked ? FLinearColor(0.45f, 0.45f, 0.45f)
            : (i == Mode->Selected ? FLinearColor(0.98f, 0.85f, 0.25f) : FLinearColor::White);
        GetTextSize(Label, W, H, Font, 1.6f);
        DrawText(Label, Color, (Canvas->SizeX - W) / 2.f, Y, Font, 1.6f);
        Y += H + 18.f;
    }
    DrawText(TEXT("Up/Down select \\u00b7 Enter play \\u00b7 M returns here from a level"),
        FLinearColor(0.7f, 0.7f, 0.7f), 16.f, Canvas->SizeY - 40.f, Font, 1.f);
}
`;

/* -------------------------------------------------------------- export --- */

const KERNEL_ROOT = 'MojuloKernel';
const SRC = `${KERNEL_ROOT}/Source/MojuloKernel`;

/** The mojulo-unreal kernel as pack files. Copied by the operator (or the
 * driver) to `<Project>/Plugins/MojuloKernel/`; the project compiles it. */
export function emitUnrealKernel() {
  return [
    { file: `${KERNEL_ROOT}/MojuloKernel.uplugin`, text: uplugin() },
    { file: `${SRC}/MojuloKernel.Build.cs`, text: buildCs() },
    { file: `${SRC}/Private/MojuloKernelModule.cpp`, text: moduleCpp() },
    { file: `${SRC}/Public/MojuloScore.h`, text: scoreH() },
    { file: `${SRC}/Private/MojuloScore.cpp`, text: scoreCpp() },
    { file: `${SRC}/Public/MojuloWalker.h`, text: walkerH() },
    { file: `${SRC}/Private/MojuloWalker.cpp`, text: walkerCpp() },
    { file: `${SRC}/Public/MojuloGameMode.h`, text: gameModeH() },
    { file: `${SRC}/Private/MojuloGameMode.cpp`, text: gameModeCpp() },
    { file: `${SRC}/Public/MojuloHUD.h`, text: hudH() },
    { file: `${SRC}/Private/MojuloHUD.cpp`, text: hudCpp() },
    { file: `${SRC}/Public/MojuloMenuGameMode.h`, text: menuH() },
    { file: `${SRC}/Private/MojuloMenuGameMode.cpp`, text: menuCpp() },
  ];
}
