import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { ICON_CELLS, ICON_DOTS, ICON_GAMMA, ICON_INK, ICON_QUANT } from './icon-dots.js';
import { bakeAll, readIcons, pathToPolys, renderModule, CELLS } from '../../scripts/build-brand-icons.mjs';
import { WORKSHOP_GROUPS, DOOR_ICONS } from '../../components/workshop-nav.jsx';

const HERE = dirname(fileURLToPath(import.meta.url));

describe('the baked door icons', () => {
  // The same promise the mark makes: given the same geometry the lattice is
  // byte-identical on any host. It is baked rather than sampled in the browser
  // precisely so it can be pinned this way.
  it('re-bakes to exactly what is committed', () => {
    expect(bakeAll()).toEqual(ICON_DOTS);
  });

  it('is not stale — the committed file IS the bake', () => {
    // Same assertion as `node scripts/build-brand-icons.mjs --check`. This is
    // the test that matters: the geometry lives in workshop-nav.jsx, so editing
    // an icon without re-baking would otherwise ship a relief that no longer
    // matches the icon it claims to be.
    expect(readFileSync(join(HERE, 'icon-dots.js'), 'utf8')).toBe(renderModule());
  });

  it('bakes every icon the nav module exports', () => {
    const exported = readIcons().map((i) => i.name).sort();
    expect(Object.keys(ICON_DOTS).sort()).toEqual(exported);
    expect(exported.length).toBeGreaterThan(15);
  });

  it('is a lattice of the declared size, with coverage above the ink floor', () => {
    expect(ICON_CELLS).toBe(CELLS);
    for (const [name, dots] of Object.entries(ICON_DOTS)) {
      expect(dots.length, name).toBeGreaterThan(20);
      for (const [c, r, hits] of dots) {
        expect(c).toBeGreaterThanOrEqual(0);
        expect(c).toBeLessThan(ICON_CELLS);
        expect(r).toBeGreaterThanOrEqual(0);
        expect(r).toBeLessThan(ICON_CELLS);
        // Stored as supersample hits, so a coverage is always a clean fraction.
        expect(Number.isInteger(hits)).toBe(true);
        expect(hits).toBeGreaterThan(0);
        expect(hits).toBeLessThanOrEqual(ICON_QUANT);
        expect(hits / ICON_QUANT).toBeGreaterThan(ICON_INK);
      }
    }
  });

  it('keeps negative space — a relief is not a blob', () => {
    // The failure this pins is the one the first pass actually hit: fattening
    // the stroke enough to give the lattice mass filled the holes in forms like
    // the gamepad and the clipboard, and every icon came out a lozenge. A
    // bounded ink fraction is what "the form survived" looks like numerically.
    for (const [name, dots] of Object.entries(ICON_DOTS)) {
      const solid = dots.filter(([, , h]) => h === ICON_QUANT).length;
      expect(solid / (ICON_CELLS * ICON_CELLS), `${name} is solid ink`).toBeLessThan(0.4);
    }
    // The gamepad's centre is hollow: its middle row must break into runs.
    const games = ICON_DOTS.GameDevIcon;
    const mid = Math.round(ICON_CELLS / 2);
    let runs = 0, prev = false;
    for (let c = 0; c < ICON_CELLS; c++) {
      const on = games.some(([dc, dr]) => dc === c && dr === mid);
      if (on && !prev) runs += 1;
      prev = on;
    }
    expect(runs).toBeGreaterThan(1);
  });

  it('the renderer gamma travels with the bake', () => {
    // Fatten (bake-side) and gamma (render-side) are one measured decision. The
    // constant lives in the generated module so a re-tune cannot land on one
    // side only.
    expect(ICON_GAMMA).toBeGreaterThan(0);
    expect(ICON_GAMMA).toBeLessThan(1);
  });

  it('is generated, and says so', () => {
    expect(readFileSync(join(HERE, 'icon-dots.js'), 'utf8')).toContain('GENERATED by scripts/build-brand-icons.mjs');
  });
});

describe('the path parser the bake depends on', () => {
  it('walks absolute and relative commands to the same place', () => {
    const abs = pathToPolys('M2 2 L10 2 L10 10 Z');
    const rel = pathToPolys('m2 2 l8 0 l0 8 z');
    expect(abs[0][0]).toEqual({ x: 2, y: 2 });
    expect(rel[0][0]).toEqual({ x: 2, y: 2 });
    // Both close back on the start point.
    expect(abs[0].at(-1)).toEqual({ x: 2, y: 2 });
    expect(rel[0].at(-1)).toEqual({ x: 2, y: 2 });
  });

  it('treats trailing pairs after a moveto as linetos', () => {
    const [poly] = pathToPolys('M0 0 4 0 4 4');
    expect(poly).toEqual([{ x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 4 }]);
  });

  it('flattens an arc onto its own circle', () => {
    // A half-circle of radius 5 centred on (5,0): every sampled point must sit
    // on that circle, or the reliefs of the six arc-bearing icons are wrong.
    const [poly] = pathToPolys('M0 0 a5 5 0 0 1 10 0');
    expect(poly.length).toBeGreaterThan(6);
    for (const p of poly) expect(Math.hypot(p.x - 5, p.y - 0)).toBeCloseTo(5, 4);
  });

  it('refuses a command it does not understand rather than skipping it', () => {
    // Silence here would mean an icon quietly losing a stroke in its relief.
    expect(() => pathToPolys('M0 0 Q4 4 8 0')).toThrow(/unsupported path command/);
  });
});

describe('a door names its icon', () => {
  it('every tile resolves to a component AND a baked lattice', () => {
    // The one drift risk in naming an icon instead of holding it: a tile could
    // name something that does not exist. Both lookups are pinned here, so a
    // typo fails in CI rather than rendering an empty plate.
    for (const group of WORKSHOP_GROUPS) {
      for (const tile of group.tiles) {
        expect(typeof DOOR_ICONS[tile.icon], `${tile.key} → ${tile.icon}`).toBe('function');
        expect(ICON_DOTS[tile.icon], `${tile.key} → ${tile.icon}`).toBeDefined();
      }
    }
  });

  it('the registry holds no icon the bake does not know', () => {
    for (const name of Object.keys(DOOR_ICONS)) expect(ICON_DOTS[name], name).toBeDefined();
  });
});
