import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { MARK_COLS, MARK_ROWS, MARK_DOTS, MARK_STROKES, MARK_INK, MARK_GRADIENT } from './mark-dots.js';
import { bakeDots, renderModule, renderIcon, COLS, ROWS } from '../../scripts/build-brand-mark.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

describe('the baked mark', () => {
  // The same promise every kernel in this tree makes: given the same inputs the
  // output is byte-identical, on any host. The mark is baked rather than sampled
  // in the browser precisely so it can be pinned this way.
  it('re-bakes to exactly what is committed', () => {
    const fresh = bakeDots();
    expect(fresh).toEqual(MARK_DOTS);
  });

  it('is a lattice of the declared size', () => {
    expect([MARK_COLS, MARK_ROWS]).toEqual([COLS, ROWS]);
    for (const [c, r, v] of MARK_DOTS) {
      expect(c).toBeGreaterThanOrEqual(0);
      expect(c).toBeLessThan(MARK_COLS);
      expect(r).toBeGreaterThanOrEqual(0);
      expect(r).toBeLessThan(MARK_ROWS);
      expect(v).toBeGreaterThan(0);
      expect(v).toBeLessThanOrEqual(1);
    }
  });

  it('reads as an m — three stems, two arches', () => {
    // The letterform is the whole point of the mark, so pin its shape rather
    // than only its checksum: a mid-height row must show three separated runs
    // of ink (the stems), and a row near the top must be one continuous run
    // (the arches, fused at the crown).
    const runs = (row, floor) => {
      let n = 0, prev = false;
      for (let c = 0; c < MARK_COLS; c++) {
        const v = MARK_DOTS.find(([dc, dr]) => dc === c && dr === row)?.[2] || 0;
        const on = v > floor;
        if (on && !prev) n += 1;
        prev = on;
      }
      return n;
    };
    expect(runs(10, 0.3)).toBe(3);   // stems
    expect(runs(3, 0.3)).toBe(1);    // crown
  });

  it('weights descend left to right', () => {
    // The three stems get lighter across the mark, which is what gives the
    // relief a light side; the radius gradient assumes it.
    const stemInk = (col) => MARK_DOTS.filter(([c, , v]) => c === col && v > 0.9).length;
    expect(stemInk(3)).toBeGreaterThan(0);
    expect(MARK_GRADIENT.maxL).toBeGreaterThan(MARK_GRADIENT.maxR);
    expect(MARK_GRADIENT.bgL).toBeGreaterThan(MARK_GRADIENT.bgR);
  });

  it('carries a solid reading of the same skeleton', () => {
    // Five strokes: two arches over three stems. The solid reading exists for
    // sizes the lattice cannot resolve; if it ever drifts from the dots it stops
    // being the same mark.
    expect(MARK_STROKES).toHaveLength(5);
    for (const s of MARK_STROKES) {
      expect(s.d).toMatch(/^M[\d.,]+[CL]/);
      expect(s.w).toBeGreaterThan(0);
      expect(s.w).toBeLessThan(MARK_COLS);
    }
    const curves = MARK_STROKES.filter((s) => s.d.includes('C'));
    expect(curves).toHaveLength(2);
  });

  it('is generated, and says so', () => {
    const src = readFileSync(join(HERE, 'mark-dots.js'), 'utf8');
    expect(src).toContain('GENERATED by scripts/build-brand-mark.mjs');
  });

  it('is not stale — the committed file IS the bake', () => {
    // Same assertion as `node scripts/build-brand-mark.mjs --check`, run in CI
    // so a hand-edit or a geometry change without a re-bake fails loudly rather
    // than shipping a mark that no longer matches its own generator.
    expect(readFileSync(join(HERE, 'mark-dots.js'), 'utf8')).toBe(renderModule());
  });

  it('keeps the ink threshold below the lightest ink cell', () => {
    // Cells below MARK_INK render as field. If the threshold ever rose above a
    // real stem's coverage the letterform would lose an edge silently.
    const stemFloor = Math.min(...MARK_DOTS.filter(([, , v]) => v > 0.5).map(([, , v]) => v));
    expect(MARK_INK).toBeLessThan(stemFloor);
  });
});

describe('the favicon', () => {
  const icon = () => readFileSync(join(HERE, '..', '..', 'app', 'icon.svg'), 'utf8');

  it('is not stale — the committed file IS the bake', () => {
    // app/icon.svg is emitted from the SAME skeleton as the nav mark, so the tab
    // can never disagree with the chrome. Hand-editing it fails here.
    expect(icon()).toBe(renderIcon());
  });

  it('is the solid reading, not the relief', () => {
    // A tab renders at 16px, which is the one size the halftone provably cannot
    // hold (MARK_RELIEF_MIN is 28). Five stroked paths, no <circle> lattice.
    const svg = renderIcon();
    expect(svg.match(/<path /g)).toHaveLength(MARK_STROKES.length);
    expect(svg).not.toContain('<circle');
  });

  it('carries literal ink, never currentColor', () => {
    // A favicon inherits no colour, so `currentColor` resolves to black — the
    // mark would vanish into its own plate. Everywhere else the mark takes
    // currentColor; here it must not.
    const svg = renderIcon();
    expect(svg).not.toContain('currentColor');
    expect(svg).toContain('#e8edf2');   // --ink-primary
    expect(svg).toContain('#07090c');   // --bay-void, the plate
  });

  it('spends no signal hue on the mark', () => {
    // Teal is --live and means "it exists and it runs"; amber is --forge. A hue
    // is a state claim, and a logo makes no state claim. The retired three-card
    // mark was a teal gradient, which is exactly the confusion 7c removed.
    const svg = renderIcon().toLowerCase();
    for (const hue of ['#5eead4', '#2dd4bf', '#f4a86a', 'lineargradient']) {
      expect(svg).not.toContain(hue);
    }
  });

  it('parses as XML — no double hyphen inside the banner comment', () => {
    // Not pedantry: an XML comment containing `--` makes librsvg reject the
    // WHOLE document, so an icon naming `--bay-void` in its banner does not
    // render at all rather than rendering imperfectly. The first bake did this.
    const svg = renderIcon();
    for (const [, body] of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
      expect(body).not.toMatch(/--/);
    }
  });

  it('keeps the mark square-fitted inside the plate, not squashed', () => {
    // The mark is 18:15. Fitting the longer axis and centring the other is what
    // keeps it from being stretched into a square plate; a non-uniform scale
    // here would mean someone reached for scale(x, y).
    expect(renderIcon()).toMatch(/scale\(\d+(\.\d+)?\)/);
  });
});
