import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { MARK_COLS, MARK_ROWS, MARK_DOTS, MARK_STROKES, MARK_INK, MARK_GRADIENT } from './mark-dots.js';
import { bakeDots, renderModule, COLS, ROWS } from '../../scripts/build-brand-mark.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

describe('the baked mark', () => {
  // The same promise every kernel in this tree makes: given the same inputs the
  // output is byte-identical, on any host. The mark is baked rather than sampled
  // in the browser precisely so it can be pinned this way.
  it('re-bakes to exactly what is committed', () => {
    const fresh = bakeDots();
    expect(fresh).toEqual(MARK_DOTS);
  });

  it('is a lattice of the declared size', () => {
    expect([MARK_COLS, MARK_ROWS]).toEqual([COLS, ROWS]);
    for (const [c, r, v] of MARK_DOTS) {
      expect(c).toBeGreaterThanOrEqual(0);
      expect(c).toBeLessThan(MARK_COLS);
      expect(r).toBeGreaterThanOrEqual(0);
      expect(r).toBeLessThan(MARK_ROWS);
      expect(v).toBeGreaterThan(0);
      expect(v).toBeLessThanOrEqual(1);
    }
  });

  it('reads as an m — three stems, two arches', () => {
    // The letterform is the whole point of the mark, so pin its shape rather
    // than only its checksum: a mid-height row must show three separated runs
    // of ink (the stems), and a row near the top must be one continuous run
    // (the arches, fused at the crown).
    const runs = (row, floor) => {
      let n = 0, prev = false;
      for (let c = 0; c < MARK_COLS; c++) {
        const v = MARK_DOTS.find(([dc, dr]) => dc === c && dr === row)?.[2] || 0;
        const on = v > floor;
        if (on && !prev) n += 1;
        prev = on;
      }
      return n;
    };
    expect(runs(10, 0.3)).toBe(3);   // stems
    expect(runs(3, 0.3)).toBe(1);    // crown
  });

  it('weights descend left to right', () => {
    // The three stems get lighter across the mark, which is what gives the
    // relief a light side; the radius gradient assumes it.
    const stemInk = (col) => MARK_DOTS.filter(([c, , v]) => c === col && v > 0.9).length;
    expect(stemInk(3)).toBeGreaterThan(0);
    expect(MARK_GRADIENT.maxL).toBeGreaterThan(MARK_GRADIENT.maxR);
    expect(MARK_GRADIENT.bgL).toBeGreaterThan(MARK_GRADIENT.bgR);
  });

  it('carries a solid reading of the same skeleton', () => {
    // Five strokes: two arches over three stems. The solid reading exists for
    // sizes the lattice cannot resolve; if it ever drifts from the dots it stops
    // being the same mark.
    expect(MARK_STROKES).toHaveLength(5);
    for (const s of MARK_STROKES) {
      expect(s.d).toMatch(/^M[\d.,]+[CL]/);
      expect(s.w).toBeGreaterThan(0);
      expect(s.w).toBeLessThan(MARK_COLS);
    }
    const curves = MARK_STROKES.filter((s) => s.d.includes('C'));
    expect(curves).toHaveLength(2);
  });

  it('is generated, and says so', () => {
    const src = readFileSync(join(HERE, 'mark-dots.js'), 'utf8');
    expect(src).toContain('GENERATED by scripts/build-brand-mark.mjs');
  });

  it('is not stale — the committed file IS the bake', () => {
    // Same assertion as `node scripts/build-brand-mark.mjs --check`, run in CI
    // so a hand-edit or a geometry change without a re-bake fails loudly rather
    // than shipping a mark that no longer matches its own generator.
    expect(readFileSync(join(HERE, 'mark-dots.js'), 'utf8')).toBe(renderModule());
  });

  it('keeps the ink threshold below the lightest ink cell', () => {
    // Cells below MARK_INK render as field. If the threshold ever rose above a
    // real stem's coverage the letterform would lose an edge silently.
    const stemFloor = Math.min(...MARK_DOTS.filter(([, , v]) => v > 0.5).map(([, , v]) => v));
    expect(MARK_INK).toBeLessThan(stemFloor);
  });
});
