import { register } from 'node:module';
import { pathToFileURL } from 'node:url';
register(pathToFileURL('/Users/fombico/Documents/mojulo/control/scripts/mcp-stdio-loader.mjs').href);
import { writeFileSync } from 'node:fs';
import puppeteer from 'puppeteer-core';
const { assembleRiverScene } = await import('/Users/fombico/Documents/mojulo/control/lib/graph/landscape/river-view.js');
const { emitThreeWorld } = await import('/Users/fombico/Documents/mojulo/control/lib/graph/scene/scene-three.js');
const { resolveChromium, CHROMIUM_LAUNCH_ARGS, CHROMIUM_WEBGL_ARGS } = await import('/Users/fombico/Documents/mojulo/control/lib/graph/scene/chromium.js');
const kind = process.argv[2], out = process.argv[3];
const payload = assembleRiverScene({ kind: 'river-view', scenario: kind, seed: 3 }, {});
const html = emitThreeWorld({ ...payload, inline: true });
writeFileSync(out.replace(/\.png$/, '.html'), html);
const browser = await puppeteer.launch({ executablePath: await resolveChromium(), headless: true, args: [...CHROMIUM_LAUNCH_ARGS, ...CHROMIUM_WEBGL_ARGS] });
const page = await browser.newPage();
await page.setViewport({ width: 1120, height: 780, deviceScaleFactor: 2 });
await page.goto('file://' + out.replace(/\.png$/, '.html'), { waitUntil: 'domcontentloaded' });
await new Promise((r) => setTimeout(r, 3000));
await page.evaluate(() => { for (const s of ['#ctrl', '.ctrl', '.hint', '.controls', '.hud']) for (const e of document.querySelectorAll(s)) e.style.display = 'none'; });
writeFileSync(out, Buffer.from(await page.screenshot({ type: 'png' })));
await browser.close(); console.log('wrote', out, kind);
