import { buildSand } from './kernel.mjs';
import { seedHopper } from './scene.mjs';
import { printWaveManji } from '../../../lib/graph/polygonizer/wave-manji.js';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
const glyph=printWaveManji({singularity:{x:0,y:0,z:0},script:'mandala',params:{N:3,radius:1,lobeDepth:0.08},samples:12}).polylines.map(l=>l.map(p=>[p.x,p.y]));
const output=resolve(process.argv[2]||'scripts/spikes/sand/preview.html');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sleeping sand · Mojulo spike</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#10151c;color:#eef0e8;font:15px system-ui}main{max-width:1120px;margin:30px auto;padding:0 22px}.eyebrow{color:#e1bc7f;font:12px monospace;letter-spacing:2px}h1{font-size:38px;letter-spacing:-1px;margin:12px 0}p{max-width:900px;color:#aeb7c0;line-height:1.6}.controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:18px 0}button,select{font:inherit;background:#24303c;color:#eef0e8;border:1px solid #43515f;padding:9px 12px;border-radius:7px}button.primary{background:#dfb776;color:#151b22;border-color:#dfb776}label{display:flex;gap:8px;align-items:center}input{accent-color:#dfb776}canvas#view{display:block;width:100%;height:auto;background:#151f2a;border:1px solid #394653;border-radius:10px;touch-action:none;image-rendering:pixelated}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}.metric{background:#1b2530;padding:14px;border-radius:8px}.metric strong{display:block;font:22px monospace;color:#e7c58a}.metric span{color:#99a9b8;font-size:12px}.legend{font-size:13px}.hint{color:#e7c58a}@media(max-width:600px){.metrics{grid-template-columns:repeat(2,1fr)}h1{font-size:30px}}</style>
<main><div class="eyebrow">MOJULO / PARTICLE VACUUM / ISOLATED SPIKE</div><h1>Sleeping sand</h1><p>Grains fall under gravity, land inelastically, slide against Coulomb friction, then sleep. Friction, not the grid, sets the heap angle; lowering it under a settled heap starts an avalanche. A local edit wakes only the grains whose footing it changes. Open the hopper gate to watch a supported pile turn into a stream.</p>
<div class="controls"><button class="primary" id="gate">Open gate</button><button id="pause">Pause</button><button id="reset">Reset hopper</button><button id="pour">Continuous pour: off</button></div>
<div class="controls"><label>Brush <select id="brush"><option value="1">Add sand</option><option value="0">Dig / remove support</option><option value="2">Build terrain</option></select></label><label>Size <input id="size" type="range" min="1" max="8" value="3"></label><label>Speed <input id="speed" type="range" min="1" max="4" step="1" value="1"></label><label>Sliding μ <input id="mu" type="range" min="0.2" max="1" step="0.01" value="0.58"><span id="muDeg"></span></label><label>Static μs <input id="mus" type="range" min="0.2" max="1.2" step="0.01" value="0.67"><span id="musDeg"></span></label><label>Depiction <select id="depiction"><option value="cells">Compact grains</option><option value="waves">Frozen wave glyphs</option></select></label></div>
<canvas id="view" width="1080" height="720" aria-label="Interactive side view of a sand hopper. Pointer dragging adds sand, digs, or builds terrain."></canvas>
<div class="metrics"><div class="metric"><strong id="grains">0</strong><span>grains · bounded grid</span></div><div class="metric"><strong id="awake">0</strong><span>pending cells · sleeping pile does no grain work</span></div><div class="metric"><strong id="checks">0</strong><span>grain checks / last tick</span></div><div class="metric"><strong id="cost">0</strong><span>simulation ms / tick · excludes drawing</span></div></div>
<p class="legend">Gold = sand · slate = terrain · cell size is the grain diameter. <span class="hint">Drag in the sandbox to edit. Dig under a heap to trigger a collapse.</span></p>
<p>2D granular approximation: integer gravity with a terminal speed, work–energy Coulomb friction (a slide gains a cell of energy per cell dropped and pays μ per cell across, so flows stop below atan μ), static friction μs that lets a resting grain give way on steeper ground, and seeded left/right choices on a fixed simulation tick. It conserves grains during motion. The wave option reuses a cached Mojulo wave-manji glyph for appearance; it does not change the sand rules. No particle-pair collision solver, fluid simulation, or production level integration.</p></main>
<script>
const buildSand=${buildSand.toString()},seedHopper=${seedHopper.toString()},glyph=${JSON.stringify(glyph)};
const $=id=>document.getElementById(id),canvas=$('view'),ctx=canvas.getContext('2d');
const small=document.createElement('canvas');small.width=180;small.height=120;const mini=small.getContext('2d'),pixels=mini.createImageData(180,120);
const stamp=document.createElement('canvas');stamp.width=16;stamp.height=16;const sc=stamp.getContext('2d');sc.strokeStyle='#e5c28a';sc.lineWidth=1.2;for(const l of glyph){sc.beginPath();l.forEach(([x,y],i)=>{const px=8+x*5.5,py=8+y*5.5;i?sc.lineTo(px,py):sc.moveTo(px,py)});sc.stroke()}
let sand,gate,open=false,paused=false,pouring=false,dirty=true,pointer=null,last=null,accumulator=0,metric={checked:0,moved:0},cost=0;
const deg=v=>(Math.atan(v)*180/Math.PI).toFixed(1)+'°';
function friction(){let mu=+$('mu').value,mus=+$('mus').value;if(mus<mu){mus=mu;$('mus').value=mu}$('muDeg').textContent=deg(mu);$('musDeg').textContent=deg(mus);return {friction:mu,staticFriction:mus}}
$('mu').oninput=$('mus').oninput=()=>{sand.tune(friction());dirty=true};
function reset(){sand=buildSand(friction());gate=seedHopper(sand);open=false;pouring=false;$('gate').textContent='Open gate';$('pour').textContent='Continuous pour: off';accumulator=0;metric={checked:0,moved:0};cost=0;dirty=true}
function paint(){const cells=sand.cells;ctx.imageSmoothingEnabled=false;for(let i=0;i<cells.length;i++){const v=cells[i],j=i*4,t=((i*17)^Math.floor(i/180)*37)&15;const color=v===1?[218+t,176+t,111+t]:v===2?[89,109,127]:[21,31,42];pixels.data[j]=color[0];pixels.data[j+1]=color[1];pixels.data[j+2]=color[2];pixels.data[j+3]=255}
if($('depiction').value==='waves'){ctx.fillStyle='#151f2a';ctx.fillRect(0,0,1080,720);for(let i=0;i<cells.length;i++){const x=i%180*6,y=Math.floor(i/180)*6;if(cells[i]===2){ctx.fillStyle='#596d7f';ctx.fillRect(x,y,6,6)}else if(cells[i]===1)ctx.drawImage(stamp,x,y,6,6)}}else{mini.putImageData(pixels,0,0);ctx.drawImage(small,0,0,1080,720)}
const stats=sand.stats();$('grains').textContent=stats.grains.toLocaleString();$('awake').textContent=stats.active.toLocaleString();$('checks').textContent=metric.checked.toLocaleString();$('cost').textContent=cost.toFixed(3);dirty=false}
function edit(e){const r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*180),y=Math.floor((e.clientY-r.top)/r.height*120);sand.brush(x,y,+$('size').value,+$('brush').value);dirty=true}
canvas.onpointerdown=e=>{pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);edit(e)};canvas.onpointermove=e=>{if(pointer===e.pointerId)edit(e)};canvas.onpointerup=canvas.onpointercancel=()=>pointer=null;
$('gate').onclick=()=>{if(!open){for(const [x,y]of gate)sand.set(x,y,0);open=true;$('gate').textContent='Close gate'}else{let blocked=false;for(const [x,y]of gate){if(sand.cells[y*180+x]===1)blocked=true;else sand.set(x,y,2)}if(blocked){$('gate').textContent='Close gate (sand in opening)'}else{open=false;$('gate').textContent='Open gate'}}dirty=true};
$('reset').onclick=reset;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Play':'Pause';accumulator=0};$('pour').onclick=()=>{pouring=!pouring;$('pour').textContent='Continuous pour: '+(pouring?'on':'off')};$('depiction').onchange=()=>dirty=true;
function frame(now){if(last===null)last=now;const delta=Math.min(0.1,(now-last)/1000);last=now;if(!paused){accumulator+=delta*60*+$('speed').value;let work=0;while(accumulator>=1&&work<12){if(pouring)sand.brush(90,3,2,1);const beforeActive=sand.stats().active;const start=performance.now();metric=sand.step();const elapsed=performance.now()-start;cost=metric.checked?0.9*cost+0.1*elapsed:elapsed;if(metric.moved||pouring||dirty||metric.active!==beforeActive)dirty=true;accumulator--;work++}if(work===12)accumulator=Math.min(accumulator,1)}if(dirty)paint();requestAnimationFrame(frame)}reset();paint();requestAnimationFrame(frame);
</script></html>`;
mkdirSync(dirname(output),{recursive:true});writeFileSync(output,html);console.log(output);
