/**
 * The ANIMAL realm of the figure system — a quadruped/biped creature minted as a
 * sketch, the peer of the human protoform.
 *
 * One move makes it: the SAME manji armature the human figure rides, with the spine
 * reoriented HORIZONTAL. Everything downstream is shared — the flesh/weld model, the
 * proto-skull, the proto-foot, the coat pelage, and the render path itself
 * (`buildAnimal` emits the figure's own `{polylines, stroke}` ring-part currency, so
 * `renderAnimalToSvg` goes through the exact figure mesher: litFaces → projectFaces →
 * drawPolys, no second renderer).
 *
 * Two doors, and the difference is the BODY MODEL, not the species list:
 *   - `archetype` alone → the cheap OVERLAP path. Each bone/joint/skull is its own
 *     ring-stack shell, depth-sorted. Fast, reads as a clear silhouette, seams show.
 *     The lineup / iteration door.
 *   - `species` (a ZOO_BUILDS recipe) → the HERO path: one welded single skin plus a
 *     welded skull, dressed with coat / markings / face / tail. Both doors accept
 *     `opts` on top, so a species is a STARTING POINT, not a fixed thing.
 *
 * Persists as `kind: 'animal'` in the `sketches` table — a recipe, not a render:
 * `{ archetype, opts, view, elev, crop }` regenerated by the kernel on every read.
 * Iterate in place with `update_sketch`; do not re-mint to change a knob.
 *
 * Registered as the `animal` kind of `mint_solid` (family 'creature'); no tool of its
 * own. See lib/graph/solid-vocab/animal.md for the parameter manual.
 */

import { SketchRepository } from '@/lib/db/repositories/sketches';
import { SketchFolderRepository } from '@/lib/db/repositories/sketch-folders';
import { renderAnimalToSvg, ANIMAL_VIEWS } from '@/lib/graph/polygonizer/figure-render';
import { ZOO_BUILDS } from '@/lib/graph/polygonizer/figure-animal-build';
import { QUADRUPED_ARCHETYPES } from '@/lib/graph/polygonizer/figure-animal';
import { groundedFeet } from '@/lib/graph/polygonizer/figure-animal-foot';
import { SPECIES as FAUNA, speciesPlan } from '@/lib/graph/fauna/species';
import { BUG_SPECIES, bugParams, resolveBug, assembleBug } from '@/lib/graph/bugs/species';
import { bugByName } from '@/lib/graph/bugs/entries';
import { createLayeredPlanHandler } from '@/lib/mcp/tools/layered';

const ARCHETYPES = Object.keys(QUADRUPED_ARCHETYPES);
const SPECIES = [...new Set([...Object.keys(FAUNA), ...Object.keys(BUG_SPECIES), ...Object.keys(ZOO_BUILDS)])];

// an arthropod's stance word from its leg count (all legs, grounded or not)
const legStance = (n) => ({ 6: 'hexapod', 8: 'octopod', 10: 'decapod', 14: 'isopod' }[n] || (n > 14 ? 'myriapod' : `${n}-legged`));

// Deep-merge the caller's `opts` over a species recipe's own, one level into each
// cfg block — so `{ skullCfg: { length: 0.3 } }` retunes ONE knob instead of
// replacing the species' whole skull. Arrays and scalars replace outright.
function mergeOpts(base, over) {
  const out = { ...base };
  for (const [k, v] of Object.entries(over)) {
    const b = out[k];
    out[k] = (v && typeof v === 'object' && !Array.isArray(v) && b && typeof b === 'object' && !Array.isArray(b))
      ? { ...b, ...v }
      : v;
  }
  return out;
}

export async function createAnimalHandler(input) {
  if (!input || typeof input !== 'object') throw new Error('the animal kind requires { title }');
  const { title, archetype, view, elev, crop, background, ref, folder_ref: folderRef } = input;
  let { species } = input;
  let { bug } = input;
  if (typeof bug === 'string' && /^\s*\{/.test(bug)) { try { bug = JSON.parse(bug); } catch { /* rejected below */ } }
  // Defensive transport parse: some MCP clients deliver object-valued params as
  // JSON strings (same guard as createFigureHandler).
  let { opts } = input;
  if (typeof opts === 'string' && /^\s*[{[]/.test(opts)) {
    try { opts = JSON.parse(opts); } catch { /* leave as string; rejected below */ }
  }
  if (!title || typeof title !== 'string') throw new Error('`title` is required (string)');
  if (ref !== undefined && (typeof ref !== 'string' || !/^[A-Za-z0-9_-]{1,64}$/.test(ref))) {
    throw new Error('`ref` must be 1-64 chars of [A-Za-z0-9_-] if provided');
  }
  // an arthropod by the name people say ('a ladybug', 'crawdad'), or one not built yet by its stand-in ('wasp' → the
  // honey bee): resolved here and echoed back, so a direct mint needs no search round trip
  let named = null;
  if (typeof species === 'string' && !SPECIES.includes(species)) {
    named = bugByName(species);
    if (named) { named = { asked: species, ...named }; species = named.id; }
  }
  if (species !== undefined && species !== null && !SPECIES.includes(species)) {
    throw new Error(`\`species\` must be one of ${SPECIES.join(', ')} — or omit it and pass \`archetype\` for the bare body`);
  }
  if (archetype !== undefined && archetype !== null && !ARCHETYPES.includes(archetype)) {
    throw new Error(`\`archetype\` must be one of ${ARCHETYPES.join(', ')}`);
  }
  if (bug !== undefined && bug !== null && (typeof bug !== 'object' || Array.isArray(bug))) {
    throw new Error('`bug` describes an arthropod nobody has built: { like?, order?, traits?: { head, trunk, tail, legs, foreLegs, hindLegs, antennae, mouth, eyes, palps, wings, wingPose, extras }, length?, name?, colors?, over? }');
  }
  if (species === undefined && archetype === undefined && (bug === undefined || bug === null)) {
    throw new Error(`pass \`species\` (a dressed recipe: ${SPECIES.join(', ')}) or \`archetype\` (a bare body: ${ARCHETYPES.join(', ')}) — or \`bug\` (an arthropod nobody has built, by its order and part forms)`);
  }
  if (opts !== undefined && opts !== null && (typeof opts !== 'object' || Array.isArray(opts))) {
    throw new Error('`opts` must be an object of buildAnimal knobs (skin, armatureCfg, skullCfg, footCfg, coat, face, tailCfg, …)');
  }
  if (view !== undefined && view !== null && typeof view !== 'number' && !ANIMAL_VIEWS.includes(view)) {
    throw new Error(`\`view\` must be a number (azimuth°) or one of ${ANIMAL_VIEWS.join(', ')}`);
  }
  if (elev !== undefined && elev !== null && (typeof elev !== 'number' || elev < -89 || elev > 89)) {
    throw new Error('`elev` must be a number in [-89, 89] (camera elevation in degrees)');
  }
  if (crop !== undefined && crop !== null && crop !== 'head') {
    throw new Error("`crop` must be 'head' (a face study) or omitted (the whole animal)");
  }
  if (folderRef !== undefined && folderRef !== null) {
    if (!SketchFolderRepository.getByRef(folderRef)) throw new Error(`Folder '${folderRef}' not found`);
  }

  // An ARTHROPOD (lib/graph/bugs): a worked bug by `species`, or one nobody has built by `bug` (the closest worked bug
  // with the asked part forms worn over it). Both are ring plans through the layered plan door.
  if ((species && BUG_SPECIES[species]) || (bug && !species)) {
    if (opts !== undefined && opts !== null) throw new Error('`opts` are figure-body knobs; a bug is a ring plan — mint it, then tune with update_sketch on \'/plan/...\'');
    let resolved = null, B;
    // `like` by any name too ('ladybug', 'wasp' → its stand-in)
    if (bug && typeof bug.like === 'string' && !BUG_SPECIES[bug.like]) { const n = bugByName(bug.like); if (n) { named = { asked: bug.like, ...n }; bug = { ...bug, like: n.id }; } }
    try { if (bug) { resolved = resolveBug(bug); B = resolved.bauplan; } else B = bugParams(species); }
    catch (err) { throw new Error(`${err.message}`); }
    const { plan, readout } = assembleBug(B);
    const res = await createLayeredPlanHandler({
      title, plan, plan_audit: { source: 'agent' },
      ...(ref ? { ref } : {}), ...(folderRef ? { folder_ref: folderRef } : {}),
    });
    return { ...res, species: species || null, stance: legStance(readout.legPairs * 2), legs: readout.legPairs * 2, length_m: readout.length,
      ...(resolved ? { basis: resolved.basis, worn: resolved.worn, ranked: resolved.ranked } : {}),
      ...(named && named.via !== 'id' ? { resolved_from: named.via === 'stand-in'
        ? { name: named.asked, stand_in: true, note: `no ${named.wanted} is built yet: the ${named.id} stands in (it misses: ${named.misses})` }
        : { name: named.asked } } : {}) };
  }

  // A species rebuilt as a ring plan mints through the layered plan door: watertight, dialled, and
  // stored as `kind: 'layered'` with the plan beside the recipe, so `/plan/...` patches retune it.
  // An explicit `archetype` keeps the hand-tuned figure body instead.
  if (species && FAUNA[species] && !archetype) {
    if (opts !== undefined && opts !== null) {
      throw new Error(`\`opts\` are figure-body knobs; '${species}' is a ring plan now — mint it, then tune with update_sketch on '/plan/...' or '/dials/<name>'`);
    }
    const res = await createLayeredPlanHandler({
      title, plan: speciesPlan(species), plan_audit: { source: 'agent' },
      ...(ref ? { ref } : {}), ...(folderRef ? { folder_ref: folderRef } : {}),
    });
    return { ...res, species, stance: 'quadruped' };
  }

  // A species RESOLVES to (archetype, opts) here, at mint time — the stored recipe is
  // the resolved pair, so the artifact stays sovereign and re-renders identically even
  // if the ZOO_BUILDS roster is later retuned. An explicit `archetype` overrides the
  // species' own; caller `opts` merge over the species' opts.
  const spec = species ? ZOO_BUILDS[species] : null;
  const resolvedArchetype = archetype || spec?.archetype;
  const resolvedOpts = mergeOpts(spec?.opts || {}, opts && typeof opts === 'object' ? opts : {});

  const manifest = {
    kind: 'animal',
    archetype: resolvedArchetype,
    ...(Object.keys(resolvedOpts).length ? { opts: resolvedOpts } : {}),
    ...(species ? { species } : {}),
    ...(view !== undefined && view !== null ? { view } : {}),
    ...(elev !== undefined && elev !== null ? { elev } : {}),
    ...(crop ? { crop } : {}),
    ...(background !== undefined ? { background } : {}),
    title,
  };

  // Render once to validate — a bad knob fails at the mint, not at view time.
  try { renderAnimalToSvg(manifest); }
  catch (err) { throw new Error(`animal render failed: ${err.message}`); }

  const sketch = SketchRepository.create({ title, manifest, ref, folderRef: folderRef ?? null });

  // Advisory only, never a gate: animals are RENDER-ONLY geometry (open ring-strip
  // tubes, overlap assembly), so an STL closure audit will flag one. Say so at the
  // handoff instead of letting export_model be the first to mention it.
  const foreMode = resolvedOpts.armatureCfg?.foreMode ?? QUADRUPED_ARCHETYPES[resolvedArchetype]?.foreMode;
  return {
    ok: true,
    ref: sketch.ref,
    url: `/sketches/${encodeURIComponent(sketch.ref)}`,
    svgUrl: `/api/sketches/${encodeURIComponent(sketch.ref)}/svg?inline=1`,
    stance: groundedFeet(foreMode).length === 2 ? 'biped' : 'quadruped',
    notes: [
      'This is a render — open the URL (or rasterize the SVG) to SEE it, then adjust knobs via update_sketch on this same ref.',
      'Print lane: the mesh is render-only (open tubes, overlap assembly), so export_model will report it as not closed. That is advisory — suitability is yours.',
    ],
  };
}
